### ISSUE TITLE
pdf.worker.js

### ISSUE THREAD

**Issue by fanyy1990** [wojtekmaj/react-pdf#716] opened 2021-01-28 08:46 UTC
Why introduce local pdf.worker.js After that, report an Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
    at pdf.js:3008

How to solve it？

**Comment by wojtekmaj** [comment] 2021-01-29 21:16
Duplicate of #677

**Closed** 2021-01-29 21:16 UTC
Labels: duplicate, question
