### ISSUE TITLE
import react-pdf cause the mocha test to fail

### ISSUE THREAD

**Issue by varand-pez** [wojtekmaj/react-pdf#397] opened 2019-05-03 08:19 UTC
Please help me I've been stuck for many days on this. 
When I call `npm run test` I get the following error

`Error: Cannot find module 'worker-loader!./pdf.worker.entry.js'`

I have gone through the other questions, and even webpack issues page but couldn't figure out what's casing this? Already tried to use `noParse`, `exclude` and `worker-loader` but no luck.

Thanks in advance for any assistance.

**Comment by wojtekmaj** [comment] 2019-05-03 09:59
Duplicate of #273

**Closed by wojtekmaj** 2019-05-03 09:59 UTC
Labels: duplicate, question
