### ISSUE TITLE
react-pdf in antd-pro (umi dev) causes webpack to run out of memory

### ISSUE THREAD

**Issue by rolimans** [wojtekmaj/react-pdf#603] opened 2020-07-10 02:02 UTC
I'm trying to use react-pdf inside an antd-pro application to render a pdf but when i try to run the application with `npm start` the babel loader runs out of memory when tryng to import pdfkit.

I've saw a bunch of similar problems but I was not able to try their solutions because it either had to do with the babel version or with the webpack configuration. In both cases I don't really know how to modify them inside a `umi dev` project, because it uses webpack and babel, but it's a kind of wrapper.

The logs before it crashes

```

[BABEL] Note: The code generator has deoptimised the styling of  .../node_modules/pdfjs-dist/build/pdf.worker.js as it exceeds the max of 500KB.

<--- Last few GCs --->

[19155:0x5630fae50c00]    58833 ms: Scavenge 2039.8 (2049.2) -> 2039.3 (2049.5) MB, 20.1 / 0.0 ms  (average mu = 0.312, current mu = 0.296) allocation failure 
[19155:0x5630fae50c00]    58856 ms: Scavenge 2040.0 (2049.5) -> 2039.4 (2049.7) MB, 22.3 / 0.0 ms  (average mu = 0.312, current mu = 0.296) allocation failure 
[19155:0x5630fae50c00]    58875 ms: Scavenge 2040.2 (2049.7) -> 2039.7 (2050.0) MB, 17.6 / 0.0 ms  (average mu = 0.312, current mu = 0.296) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

```
 - Browser Chromium: 83
 - React-PDF version: ^4.1.0
 - React version: ^16.8.6
 - Webpack version: 4.29.6 (inside umi package.json)
 - umi version: ^3.2.2

**Comment by wojtekmaj** [comment] 2020-07-24 13:03
See #61, #496

Duplicate of #496

**Closed by wojtekmaj** 2020-07-24 13:03 UTC
