### ISSUE TITLE
[NextJS] React-pdf 7.5.0 - Vercel deployment no longer works

### ISSUE THREAD

**Issue by w-aurelien** [wojtekmaj/react-pdf#1630] opened 2023-10-06 08:31 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I just upgraded the version of react-pdf to version 7.5.0 and since then my deployments on Vercel are no longer working.

### Steps to reproduce

My next.config.com

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
    experimental: {
        serverActions: true,
    },
    webpack: (config) => {
        config.resolve.alias.canvas = false;

        return config;
    },
}

module.exports = nextConfig
```

My Component : 

```javascript
'use client';

import {Box} from "@chakra-ui/react";
import React from "react";
import { Document, Thumbnail } from 'react-pdf';
import { pdfjs } from 'react-pdf';
import useResizeObserver from "use-resize-observer";

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url,
).toString();

interface ThumbnailDocumentProps {
  ...
}

export function ThumbnailDocument({...}: ThumbnailDocumentProps) {
  const {ref, width = 1} = useResizeObserver<HTMLDivElement>();

  if (eventDocument.mimeType === 'application/pdf') {
    return <Box>
       <Document file={`/documents/${eventDocument.id}/visualiser/${eventDocument.originalName}?preview=1`}>
          <Thumbnail
            pageNumber={1}
            width={Math.max(width * 0.4, 100)} />
        </Document>
    </Box>;
  }
}
```

### Expected behavior

Deployment completed :) 
_I want to reiterate that before upgrading the version, my deployments were working correctly._

### Actual behavior

Vercel deployment error : 

```
Error: File /vercel/path0/.next/server/chunks/static/media/pdf.worker.min.6a40b659.js does not exist.
--
10:17:32.381 | at Job.emitDependency (/vercel/path0/node_modules/next/dist/compiled/@vercel/nft/index.js:1:39473)
10:17:32.381 | at async Promise.all (index 10)
10:17:32.382 | at async nodeFileTrace (/vercel/path0/node_modules/next/dist/compiled/@vercel/nft/index.js:1:35430)
10:17:32.382 | at async /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:251:28
10:17:32.383 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:105:20)
10:17:32.383 | at async collectBuildTraces (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:123:5)
10:17:32.500 | Error: Command "npm run build" exited with 1
```

### Environment

- **React-PDF version**: 7.5.0
- **React version**: 18.2

**Comment by wojtekmaj** [comment] 2023-10-06 08:46
What was the last version that worked for you?

**Comment by w-aurelien** [comment] 2023-10-06 08:56
> What was the last version that worked for you?

7.3.3

**Comment by w-aurelien** [comment] 2023-10-06 09:08
I just realized that I also upgraded the version of nextJS, so I have just conducted the following deployment tests:

- NextJS: 13.4.19 / React-pdf: 7.3.3: ✅
- NextJS: 13.4.19 / React-pdf: 7.5.0: ✅
- NextJS: 13.5.4 / React-pdf: 7.3.3: ❌
- NextJS: 13.5.4 / React-pdf: 7.5.0: ❌

**Comment by wojtekmaj** [comment] 2023-10-06 12:37
Well, that sounds like a Next.js problem to me then!

**Comment by w-aurelien** [comment] 2023-10-06 13:49
I think the two are related no? Maybe NextJs changed something that needs to be reflected in React-Pdf? Because if I remove react-pdf from my dependencies everything works correctly again.

**Comment by wojtekmaj** [comment] 2023-10-06 14:17
Clearly something used to work and stopped working. That's a bug/regression by my standards. I'll be happy to assist Vercel should they pick it up.

**Comment by jerocosio** [comment] 2023-10-06 15:43
Also getting the same error, it looks like the issue is on the latest version of Vercel NextJS: 13.5.4, as if I downgrade to NextJS: 13.5.3 I can deploy without any issues.

**Comment by JamesSingleton** [comment] 2023-10-07 05:02
I just ran into this as well verifying everything built locally. The only thing that I could find that was "worker" related in 13.5.4 was https://github.com/vercel/next.js/pull/55257 but not sure if that would cause any issues. 🤷🏼‍♂️

**Comment by sangdth** [comment] 2023-10-10 14:10
I faced this issue, and found another closed issue with similar problem, one comment suggested using the worker from cdn url and it works. I will stick with it for now.

**Comment by yadh75** [comment] 2023-10-10 22:38
i also got this problem before, i don't know if this is a good way or not, but the problem is solved

```js
// next.config.js
const CopyWebpackPlugin = require("copy-webpack-plugin");
const path = require("path");

const pdfjsDistDir = path.dirname(require.resolve("pdfjs-dist/package.json"));
const cMapsDir = path.join(pdfjsDistDir, "cmaps");
const standardFontsDir = path.join(pdfjsDistDir, "standard_fonts");
const pdfWorkerPath = path.join(pdfjsDistDir, "build", "pdf.worker.min.js");

/** @type {import('next').NextConfig} */
const nextConfig = {
    experimental: {
        serverActions: true,
    },
    webpack: (config) => {
        config.resolve.alias.canvas = false;

        config.plugins.push(
            new CopyWebpackPlugin({
                patterns: [
                    { from: cMapsDir, to: "static/chunks/pdfjs/cmaps/" },
                ],
            })
        );

        config.plugins.push(
            new CopyWebpackPlugin({
                patterns: [
                    {
                        from: standardFontsDir,
                        to: "static/chunks/pdfjs/standard_fonts/",
                    },
                ],
            })
        );

        config.plugins.push(
            new CopyWebpackPlugin({
                patterns: [
                    {
                        from: pdfWorkerPath,
                        to: "static/chunks/pdfjs/build/pdf.worker.min.js",
                    },
                ],
            })
        );

        return config;
    },
};

module.exports = nextConfig;
```

```js
// in my pdf component
...
pdfjs.GlobalWorkerOptions.workerSrc =
    "/_next/static/chunks/pdfjs/build/pdf.worker.min.js";
const documentOptions = {
    cMapUrl: "/_next/static/chunks/pdfjs/cmaps/",
    standardFontDataUrl: "/_next/static/chunks/pdfjs/standard_fonts/",
};
...
```

**Comment by sangdth** [comment] 2023-10-11 08:26
Thanks @yadh75, I tried your solution and so far it works well.

Btw what does the problem if we combine 3 pushes into one? I'm not really good at webpack:

```
        patterns: [
          { from: cMapsDir, to: 'static/chunks/pdfjs/cmaps/' },
          {
            from: standardFontsDir,
            to: 'static/chunks/pdfjs/standard_fonts/',
          },
          {
            from: pdfWorkerPath,
            to: 'static/chunks/pdfjs/build/pdf.worker.min.js',
          },
        ],
```

**Comment by yadh75** [comment] 2023-10-11 08:59
> Thanks @yadh75, I tried your solution and so far it works well.
> 
> Btw what does the problem if we combine 3 pushes into one? I'm not really good at webpack:
> 
> ```
>         patterns: [
>           { from: cMapsDir, to: 'static/chunks/pdfjs/cmaps/' },
>           {
>             from: standardFontsDir,
>             to: 'static/chunks/pdfjs/standard_fonts/',
>           },
>           {
>             from: pdfWorkerPath,
>             to: 'static/chunks/pdfjs/build/pdf.worker.min.js',
>           },
>         ],
> ```

there's no problem with that, in fact it's actually better that way

**Comment by wojtekmaj** [comment] 2023-10-13 12:03
Hey all, Vercel [confirmed](https://github.com/vercel/next.js/issues/56676#issuecomment-1761398361) it's a bug on their side. I suggest following https://github.com/vercel/next.js/issues/56676 for updates. There's nothing we can or should do on our side, so I'm closing this issue.

**Closed by wojtekmaj** 2023-10-13 12:03 UTC
Labels: bug, invalid
