### ISSUE TITLE
PDF document using data URI reloads every time component updates

### ISSUE THREAD

**Issue by DrMeers** [wojtekmaj/react-pdf#373] opened 2019-03-13 23:31 UTC
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues) -- though it may actually technically be the same bug as #353 , though I've identified a different cause/solution to what was discussed there

**Description**

`onLoadSuccess` is called every time I change the component state with a new page number

**Steps to reproduce**

1. Run code like [this example](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-single-page-with-navigation)
2. Change `file` prop to `{url: dataURI}`
3. Change pages using button navigation
4. Note that `onLoadSuccess` callback is called each time, and error console gives errors like `Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. in PageInternal (created by Context.Consumer) in Page (created by PDFViewer)`

**Expected behavior**

Change pages without reloading document

**Additional information**

Issue seems to be the equality comparison [this line](https://github.com/wojtekmaj/react-pdf/blob/79eca3691516fac21de1586b18fb919500d9950a/src/Document.jsx?L74#L74) -- because `{url: dataURI} !== {url: dataURI}` in this format.

**Environment**

 - Chrome Version 72.0.3626.119 (Official Build) (64-bit)
 - React-PDF 4.0.5
 - React 16.6.0
 - Webpack 4.25.1

**Comment by wojtekmaj** [comment] 2019-03-14 08:38
Duplicate of #308

**Comment by wojtekmaj** [comment] 2019-03-14 08:39
Please see #308 for solution - this is something React-PDF indeed should not require a specific way of coding, but sadly is, for now.

**Closed by wojtekmaj** 2019-03-14 08:38 UTC
