### ISSUE TITLE
引入CDN报错

### ISSUE THREAD

**Issue by XinYueXiao** [wojtekmaj/react-pdf#1308] opened 2023-01-31 11:20 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

![image](https://user-images.githubusercontent.com/31272499/215746031-fc1bd13e-2a64-4893-81b8-6a174363086a.png)
![image](https://user-images.githubusercontent.com/31272499/215746073-2fb03f74-564b-4f82-9c78-b3dc53d496a9.png)

### Steps to reproduce

import React from 'react'
import { Document, Page, pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

function FilePreview() {
  return (
    <div />
  )
}

export default FilePreview

### Expected behavior

安装即用不报错

### Actual behavior

安装后就报错了
Module parse failed: Unexpected character '#' (1413:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class PDFDocumentLoadingTask {
>   static #docId = 0;
| 
|   constructor() {

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment] 2023-01-31 11:44
Duplicate of #1043. Probably, I don't know your language.

**Closed by wojtekmaj** 2023-01-31 11:44 UTC
Labels: bug
