### ISSUE TITLE
Failled to load PDF file. react-pdf

### ISSUE THREAD

**Issue by hpachy** [wojtekmaj/react-pdf#533] opened 2020-03-11 09:17 UTC
Hello guys!

I'm stuck with the React-pdf package (Obviously). So the problem happen when I tried to load PDF link,
got always the same result all the time :  "Failled to load PDF file.".

./node_modules/pdfjs-dist/build/pdf.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

<img width="827" alt="Capture d’écran 2020-03-11 à 09 56 49" src="https://user-images.githubusercontent.com/24634810/76399817-9335e280-637f-11ea-9623-424b7af3426d.png">
<img width="987" alt="Capture d’écran 2020-03-11 à 09 58 03" src="https://user-images.githubusercontent.com/24634810/76399823-96c96980-637f-11ea-9696-93668c5c0ee8.png">

Very annoying when you absolute need it.
I tried a lot of things before posting my problem. I found this: http://projekty.wojtekmaj.pl/react-pdf/test/
So I tried every way to import my pdf and the way I would like to use, but he do not work ... is by the link. I would like to import my PDF through a link hosted on a AWS bucket, I don't know why, but it's look like alien and he do not load.

I would like to display PDF on computer and mobile. Oh man !? why you want to display PDF on mobile ???? It because it's very important to me to get each log of my users, I make pedagogy content and I deliver degree. The time is one of the requirement to get the degree.

Except if you have other solutions I'm stuck.

Thx for helping me! best regard

(50% of my user use computer and 50% mobile/tablette).

**Comment by wojtekmaj** [comment] 2020-03-11 13:51
Duplicate of #52

**Closed by wojtekmaj** 2020-03-11 13:51 UTC
Labels: duplicate, question
