### ISSUE TITLE
npm error code 134

### ISSUE THREAD

**Issue by DefWindowProc** [wojtekmaj/react-pdf#498] opened 2019-12-18 08:37 UTC
when I using react-pdf with create-react-app(latest version), I can't run it, e.g. "npm run start", there is a error I can't resolve, so I want to ask for solution
[traceinfo.txt](https://github.com/wojtekmaj/react-pdf/files/3977395/traceinfo.txt)

**Comment by robsco-git** [comment] 2019-12-18 09:25
I am not using Create React App although I get the same error when Babel attempts to transpile `node_modules/pdfjs-dist/`. The worker (Node.js process) reaches the set memory limit (2GB by default in my case) and can't allocate any more memory so it crashes. A solution is to exclude `pdfjs-dist` from being transpiled. In my Webpack config I have the following as a part of my `webpack.config.js`:
![image](https://user-images.githubusercontent.com/3826617/71072859-fe5c8800-2187-11ea-9c8e-5e20927581d4.png)

You will have to look into how to do the same within the context of create-react-app or "eject" (if that's still at thing).

I tried upping the worker memory limits but got to 8GB and it was still reaching the limit so that didn't end up being a solution for me.

**Comment by wojtekmaj** [comment] 2019-12-21 14:46
Duplicate of #496

**Closed by wojtekmaj** 2019-12-21 14:46 UTC
