### ISSUE TITLE
Getting an error stating "The API version "2.12.313" does not match the Worker version "2.4.456"."

### ISSUE THREAD

**Issue by FilipinoEggs** [wojtekmaj/react-pdf#966] opened 2022-03-16 01:51 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hello. I have recently used the react-pdf library and it has been working fine. However, a few days ago, without changing any code, it is not viewing the PDF as it was before when I use the Document and Page components. I instead get an error stating: "The API version "2.12.313" does not match the Worker version "2.4.456"."

I guess the API version has been automatically updated, but I am not sure how to fix this version mismatch.

### Steps to reproduce

1. Use the Document and Page components when viewing a PDF.
2. Instead of viewing a PDF as it supposed to, you will get a Failed to load PDF message on the browser.
3. The error will then be seen on the console stating "The API version "2.12.313" does not match the Worker version "2.4.456"."

### Expected behavior

The viewer will be able to show the user the PDF document.

### Actual behavior

It is not showing the PDF document and now it is giving me a version mismatch error.

### Environment

- **React-PDF version**: 5.7.1
- **React version**: 17.0.2

**Comment by wojtekmaj** [comment] 2022-03-16 19:19
Duplicate of #922

**Closed by wojtekmaj** 2022-03-16 19:19 UTC
Labels: duplicate, question
