### ISSUE TITLE
Error handling - PDFJS worker termination while loading and unmounting component.  

### ISSUE THREAD

**Issue by nicolasiscoding** [wojtekmaj/react-pdf#1062] opened 2022-10-08 23:23 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Sorry for the bump but is there any known solutions to this? This is referenced in this closed issue but seems as if the issue is stale and have a newer build then what is referenced here. It does not appear to be caught in the onLoadError. 

https://github.com/wojtekmaj/react-pdf/issues/651

<img width="398" alt="image" src="https://user-images.githubusercontent.com/9352910/194730875-58eab568-e2f8-49f5-a1ce-0c90ef2ecc4c.png">

<img width="405" alt="image" src="https://user-images.githubusercontent.com/9352910/194731025-9c4ce00c-aa1b-4612-8b2b-fe677bf0f522.png">

![image](https://user-images.githubusercontent.com/9352910/194730846-70f3fb61-94f6-4263-a9ac-7cd1c65c5480.png)

![image](https://user-images.githubusercontent.com/9352910/194730854-580ecd7b-6a70-4abd-98c3-28149ad64049.png)

### Steps to reproduce

1. Throttle Network speed in browser
2. Load a PDF
3. Navigate to another page prior to the PDF completing forcing the component to unmount
4. Get error in console

### Expected behavior

Graceful error handling or the ability to do a try catch, or an abort controller equivalent. 

### Actual behavior

React is not happy 

### Additional information

I happen to be using Gatsby, but this should persist even in vanilla React environments

### Environment

- **Browser (if applicable)**: Chrome Version 106.0.5249.103
- **React-PDF version**: 5.7.2
- **React version**:  16.14.0
- **Webpack version (if applicable)**: 5.74.0

**Comment by nicolasiscoding** [comment] 2022-10-08 23:32
And this appears to extend this: https://github.com/mozilla/pdf.js/issues/11595

**Comment by catmans1** [comment] 2022-11-08 05:36
It might related to this issue: https://github.com/wojtekmaj/react-pdf/issues/729#issuecomment-1306661079

**Comment by nicolasiscoding** [comment] 2023-05-02 04:09
Bump?

**Comment by nicolasiscoding** [comment] 2023-05-02 12:43
@wojtekmaj it seems that even if you use the onLoadError prop, pdf.js itself is still firing a error that propagates up. I can make a PR that suppresses these warnings using techniques discussed in the Mozilla thread. Is this something you think could get merged in (assuming good quality)?

**Comment by wojtekmaj** [comment] 2023-05-02 13:24
Sounds fair! Especially since I was to believe that we are already suppressing these errors :D 

Just please be aware that on main, currently, we have a completely new version so this fix would land in 7.x.

**Comment by nicolasiscoding** [comment] 2023-05-02 13:35
@wojtekmaj that's a good point. Let me verify the version when I'm back in front of this and report findings.

**Comment by IvanGerasin** [comment] 2023-05-05 11:42
Got in the same issue. It appeared in unit tests (jest+RTL) after migrating from nodeJS v14 to nodeJS v16.
react-pdf: 5.7.2

**Comment by VigneshSonaiya** [comment] 2023-08-07 09:18
HI @wojtekmaj , Still getting the same issue on version 7.3.3
![image](https://github.com/wojtekmaj/react-pdf/assets/47246527/0a98c368-e12b-43d7-8d8a-6b150e1bc5ae)

**Comment by OrlandoHurtadoBMC** [comment] 2023-08-15 21:15
Hi! I'm getting the same error here on version 7.3.3. Any workaround?

**Comment by jiangxiaoqiang** [comment] 2023-08-23 07:27
same issue with 7.3.3 too, is it possible to fixed this issue?

**Comment by monscamus** [comment] 2023-09-11 15:38
I'd love to hear and answer to this one too.

**Comment by jiangxiaoqiang** [comment] 2023-09-22 03:24
try to use the same version in whole project, I am using the different version pdf pdfjs seems trigger the issue(fisrt install pdfjs then install react-pdf but the react-pdf use old version of pdfjs).

**Comment by codewizard-dt** [comment] 2023-09-27 20:14
This is still a real issue :( There is no way that I have found to NOT log this error.  Very annoying.

**Comment by KStepanI1** [comment] 2023-10-10 17:42
![image](https://github.com/wojtekmaj/react-pdf/assets/68808519/7fb65a50-f9fb-4533-9456-446c091282df)
![image](https://github.com/wojtekmaj/react-pdf/assets/68808519/50c67794-2f23-4be2-8e3e-2afbab038fb4)
![image](https://github.com/wojtekmaj/react-pdf/assets/68808519/1dff702a-2267-40bf-a7fd-512827ad00f4)
thats work for me

**Comment by mauudev** [comment] 2023-12-12 23:55
Hi, just passing by and dropping a possible solution. We need to import the worker by this way (specified in docs):
`import { pdfjs } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url,
).toString();`

Worked for me, hope it helps.

**Comment by riancintiyo** [comment] 2024-03-04 07:21
@mauudev Thanks for dropping the code. It's indeed worked for me too. 🍻

**Comment by AlfredMadere** [comment] 2024-06-21 16:18
@mauudev have you confirmed that when you set the workerSrc as shown below you get the error, and switching to using the local script fixes it?

```typescript
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`
```

**Comment by CyberAndrii** [comment] 2024-08-21 21:44
In case someone is looking for a workaround, https://github.com/mozilla/pdf.js/issues/11595#issuecomment-1642482264

**Comment by nicolasiscoding** [comment] 2024-08-21 23:01
@CyberAndrii in the context of react, should this be added to a useEffect unmount?

**Comment by CyberAndrii** [comment] 2024-08-21 23:30
It needs to be added here

https://github.com/wojtekmaj/react-pdf/blob/5f29bfb9a952c64c9288e14506a88552772ac3cc/packages/react-pdf/src/Document.tsx#L537

But because it's not fixed in this package yet, we use [patch-package](https://www.npmjs.com/package/patch-package) to apply [the fix](https://github.com/Expensify/App/blob/ad7c1d5e394c8a9ee1ce7427233aa085350bb500/patches/react-pdf%2B7.7.3.patch).

**Closed** 2024-09-18 09:56 UTC
Labels: bug, help wanted, fresh
