### ISSUE TITLE
 Load PDF file URL facing issue in set state of component

### ISSUE THREAD

**Issue by qaisershehzad** [wojtekmaj/react-pdf#355] opened 2019-02-18 10:52 UTC
Hello @wojtekmaj , Can you please help in this.
**Description**
I am newbie to react!
When you load pdf file from URL it is causing loop in render method. I am using sample code from repo. Attached is reference screenshot. 

It is throwing below warning as well. 

"index.js:1446 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in PageInternal (created by Context.Consumer)
    in Page (at App.js:35)
"

<img width="508" alt="screen shot 2019-02-18 at 3 47 32 pm" src="https://user-images.githubusercontent.com/11673425/52946128-1eb78c80-3395-11e9-8560-deaf4189ab50.png">

**Comment by wojtekmaj** [comment] 2019-02-18 11:22
Duplicate of #353

**Comment by wojtekmaj** [comment] 2019-02-18 11:23
It's not a loop, and it's not dangerous, but is a bug indeed. Duplicate, so closing.

**Closed by wojtekmaj** 2019-02-18 11:22 UTC
