### ISSUE TITLE
low version browser throw error "Invaild regular expression"

### ISSUE THREAD

**Issue by wljray** [wojtekmaj/react-pdf#880] opened 2021-11-08 03:37 UTC
## browser throw error 
![image](https://user-images.githubusercontent.com/1441944/140680066-cb42fbdb-e5dc-4d90-addf-c49cd7cfe7a2.png)

## code in pdfjs-dist
![image](https://user-images.githubusercontent.com/1441944/140680091-7d22cdd8-e4a5-4322-b562-c78f89bda2e1.png)

pdfjs-dist 2.9.359/lib/core/xfa/html_utils.js，\\p{N}\\p{L}\\p{M}]

## Invaild regular expression
![image](https://user-images.githubusercontent.com/1441944/140680225-113af6ed-6671-4ecc-bc05-4814470a844e.png)

## need to do
react-pdf 5.5.0 Dependencies  pdfjs-dist: 2.9.359
upgrade react-pdf Dependencies，pdfjs-dist：2.10+？ or  2.8-？

**Comment by wojtekmaj** [comment] 2021-11-08 08:29
Duplicate of #844

**Closed by wojtekmaj** 2021-11-08 08:29 UTC
