### ISSUE TITLE
pdf.js requests for /[object%20Object] before loading proper URL

### ISSUE THREAD

**Issue by grgr** [wojtekmaj/react-pdf#10] opened 2016-12-28 14:56 UTC
Hello, I am getting the following error when trying to load a pdf:

pdf.js:817 GET http://localhost:3000/[object%20Object] Util_loadScript @ pdf.js:817loader @ pdf.js:8081setupFakeWorkerGlobal @ pdf.js:8085PDFWorker_setupFakeWorker @ pdf.js:8267PDFWorker_initialize @ pdf.js:8260PDFWorker @ pdf.js:8166getDocument @ pdf.js:7646loadDocument @ react-pdf.js:195handleFileLoad @ react-pdf.js:138componentDidMount @ react-pdf.js:89(anonymous function) @ ReactCompositeComponent.js:264measureLifeCyclePerf @ ReactCompositeComponent.js:74(anonymous function) @ ReactCompositeComponent.js:263notifyAll @ CallbackQueue.js:67close @ ReactReconcileTransaction.js:81closeAll @ Transaction.js:204perform @ Transaction.js:151perform @ Transaction.js:138perform @ ReactUpdates.js:90flushBatchedUpdates @ ReactUpdates.js:173closeAll @ Transaction.js:204perform @ Transaction.js:151batchedUpdates @ ReactDefaultBatchingStrategy.js:63enqueueUpdate @ ReactUpdates.js:201enqueueUpdate @ ReactUpdateQueue.js:25enqueueSetState @ ReactUpdateQueue.js:210ReactComponent.setState @ ReactComponent.js:64_onChange @ Pages.jsx:17EventEmitter.emit @ events.js:74emitChange @ PageStore.js:58(anonymous function) @ PageStore.js:78_invokeCallback @ Dispatcher.js:198dispatch @ Dispatcher.js:174handleServerAction @ AppDispatcher.js:15loadedPages @ PageActionCreators.js:10(anonymous function) @ WebAPIUtils.js:66Request.callback @ client.js:721(anonymous function) @ client.js:536Emitter.emit @ index.js:133xhr.onreadystatechange @ client.js:825

**Comment by wojtekmaj** [comment] 2017-02-04 09:51
Hi grgr, terribly sorry for the wait.

Are you sure you have the newest version available? I'm unable to reproduce this. Would you please provide steps to reproduce, if possible, using my (mini-test suite)[http://projekty.wojtekmaj.pl/react-pdf/test/] (which I hope covers all functionalities)?

I have a feeling it could be an issue that only uncovers itself on localhost, but I'm unable to test this at the moment...

Thank you for your help!

**Comment by grgr** [comment] 2017-02-06 10:20
Hi Wojtek,

no problem! I used the newest version. I am kind of busy at the moment, but I will try to test again.

**Comment by wojtekmaj** [comment] 2017-07-12 02:03
Hey! I believe that will be fixed in an incoming release. If you want to check this, temporairly change your package.json so it would say
`"react-pdf": "git+ssh://git@github.com/wojtekmaj/react-pdf.git#fix-file-undefined"`

Let me know what you think!

**Comment by wojtekmaj** [comment] 2017-07-14 02:16
Fixed in 1.7.0.

**Closed by wojtekmaj** 2017-07-14 02:16 UTC
Labels: bug
