### ISSUE TITLE
Flickering issue when scaling the entire pdf

### ISSUE THREAD

**Issue by ShashanKV98** [wojtekmaj/react-pdf#1760] opened 2024-04-13 07:58 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi. I had some issues when dealing with zooming a document with all pages in a column (not just a single page). I browsed the issues in this repo, and found a sandbox link from @wojtekmaj https://github.com/wojtekmaj/react-pdf/issues/875#issuecomment-977975073. 

This was for a single page in the viewport, so I extended it to include all the pages. The first page seems to render just fine as I use the slider, but the rest of the pages tend to flicker a lot. I've been on this for days but couldn't figure out if this is because of React or `page.render` refreshing the entire page from scratch at every new scale value or something else that I'm missing.

I'm also curious about the recommended approach for handling zooming with this library.  Is it possible to get it close to how pdf.js viewer handles zooming?

Thanks and appreciate the work put into this library.

### Steps to reproduce

Attached a codesandbox link showing this behavior.

https://codesandbox.io/p/sandbox/react-pdf-prevent-flash-with-scale-forked-pwcw8z

### Expected behavior

Flickering for all pages is supposed to be minimal to none

### Actual behavior

The first page doesn't flicker but the subsequent pages do.

### Environment

- **Browser (if applicable)**: Edge, Chrome
- **React-PDF version**: 7.7.1
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by justinblack020** [comment] 2024-05-16 05:15
Have a solution been posted for this? Would love to see a working fix for rendering the whole pdf without flashes.

**Comment by gfargo** [comment] 2024-06-05 13:53
Having a similar issue, I've tried all of the provided solutions regarding hiding the canvas while the PDF is rendering e.g. #1340 & #1279 however these do not have any impact on the canvas disappearing when "zooming" the document.

The [demo PDFJS ](https://mozilla.github.io/pdf.js/web/viewer.html) does not have this issue and it's creating horrible UIX when zooming/panning around a single page PDF.  

From what I can tell, this wasn't an issue when using `renderMode="svg"` however that has been deprecated in the newer versions 😕 any guidance from others would be greatly appreciated!

**Comment by jblack020** [comment] 2024-06-05 17:07
This solution worked for me, albeit I have no idea why since this was quite long ago on a project I've since stopped working on. I'm quite new to React in general, but perhaps this may be of use. 

My main PDFView component:
`export const PDFView = ({ pdfURL }) => {
  const [numPages, setNumPages] = useState(null)

  // Config variables
  const initialWidth = 405 
  const stepSize = 0.5
  const magnifierMax = 4

  const { scale, newScale, pageVisible, scaleUp, scaleDown, scaleReset, togglePageVisibility } =
    usePDFScaling(initialWidth, stepSize, magnifierMax)

  useElectronAPI(scaleUp, scaleDown, scaleReset)

  return (
    <Document file={pdfURL} onLoadSuccess={({ numPages }) => setNumPages(numPages)}>
      {numPages &&
        Array.from(new Array(numPages), (_el, index) => (
          <React.Fragment key={`container_${index + 1}`}>
            <Page
              className={`mb-2 ${pageVisible ? 'visible' : 'hidden'}`}
              key={`front_page_${index + 1}`}
              pageNumber={index + 1}
              scale={pageVisible ? scale : newScale}
              width={initialWidth}
              onRenderSuccess={pageVisible ? null : togglePageVisibility}
            />
            <Page
              className={`mb-2 ${pageVisible ? 'hidden' : 'visible'}`}
              key={`back_page_${index + 1}`}
              pageNumber={index + 1}
              scale={pageVisible ? newScale : scale}
              width={initialWidth}
              onRenderSuccess={pageVisible ? togglePageVisibility : null}
            />
          </React.Fragment>
        ))}
    </Document>
  )
}
`
useElectronAPI hook:
`export const useElectronAPI = (scaleUp, scaleDown, scaleReset) => {
  useEffect(() => {
    const handleZoom = (_event, action) => {
      switch (action) {
        case 'zoom-in':
          scaleUp()
          break
        case 'zoom-out':
          scaleDown()
          break
        case 'zoom-reset':
          scaleReset()
          break
      }
    }
    window.electronAPI.onMenuAction(handleZoom)

    return () => {
      window.electronAPI.removeMenuActionListener(handleZoom)
    }
  }, [scaleUp, scaleDown, scaleReset])
}
`

usePDFScaling hook:
`export const usePDFScaling = (initialWidth, stepSize, magnifierMax) => {
  const [scale, setScale] = useState(1.0)
  const [newScale, setNewScale] = useState(1.0)
  const [pageVisible, setPageVisible] = useState(true)

  const minWidth = initialWidth / magnifierMax
  const maxWidth = initialWidth * magnifierMax

  const scaleUp = () => {
    setNewScale((prevScale) => Math.min(prevScale + stepSize, maxWidth / initialWidth))
  }

  const scaleDown = () => {
    setNewScale((prevScale) => Math.max(prevScale - stepSize, minWidth / initialWidth))
  }

  const scaleReset = () => {
    const windowWidth = window.innerWidth
    const resetScale = (windowWidth * 0.45) / initialWidth
    setNewScale(resetScale)
    setScale(resetScale)
  }

  useEffect(() => {
    scaleReset()
  }, [])

  const togglePageVisibility = () => {
    if (newScale !== scale) {
      setPageVisible(!pageVisible)
      setScale(newScale)
    }
  }

  return { scale, newScale, pageVisible, scaleUp, scaleDown, scaleReset, togglePageVisibility }
}
`

**Comment by ShashanKV98** [comment] 2024-06-05 19:46
Thanks. But it seems to have the same issue. I switched the electron API part with buttons in react for scaling. I am beginning to think that since `page.render` re creates from scratch, pages with heavy graphics tend to flicker or take time to render. I wonder if it's possible to just render the portion of the pdf in the viewport and not all the pages with every scale change or maybe utilizing an offscreencanvas, but I'm not sure how to go about it.

**Comment by wojtekmaj** [comment] 2024-06-06 10:11
Duplicate of #1705
Duplicate of #875
Duplicate of #418

**Closed by wojtekmaj** 2024-06-06 10:11 UTC
Labels: question

**Comment by ShashanKV98** [comment] 2024-06-06 10:20
Hi @wojtekmaj I've seen those issues but I just can't get the performance to be even close to how pdfjs does it (seems like it only renders the text part) . The conditional rendering does a decent job but it is not robust for bigger files.  Can you please maybe point me in the direction of how to handle this or if you have any ideas I might try?

**Comment by blueskoo** [comment] 2025-02-08 17:48
hi  [@rsshilli](https://github.com/rsshilli), the point is only render textLayer and annotationLayer of pages appeared in viewport which has heavy children dom nodes.  So my solution is always tracing pages in viewport and set properties of 'renderTextLayer' and 'renderAnnotationLayer' dynamically.

1.  for Document component, I use framer motion in my project to tracing inView state
```
<Document inputRef={refPdfDoc} options={PDFDocOptions} className={'flex-1 flex flex-col items-center gap-3 overflow-hidden overflow-y-scroll h-full'} file={pdfSrc} onLoadSuccess={onDocumentLoadSuccess}>
      {[...Array(numPages).keys()].map(p => (
        <motion.div key={p} onViewportEnter={e => {
          if (!docRenderFinished) {
            tempPipeEnter.push(p+1)
          } else {
            setTempPipeEnter([...tempPipeEnter, p + 1])
          }
        }} onViewportLeave={async (e) => {
          if (!docRenderFinished) {
            tempPipeLeave.push(p + 1)
          } else {
            setTempPipeLeave([...tempPipeLeave, p + 1])
          }
        }} viewport={{root: refPdfDoc, once: false, amount: 0.1}}>
          <PdfPage root={refPdfDoc} pageNumber={p + 1} totalNumber={numPages} scale={scale} currentInView={Array.from(currentInView)} inViewAmount={inViewAmount} customRender={textRenderer}/>
        </motion.div>
      ))}
</Document>
```
2. for PdfPage component

```
useEffect(() => {
    const shouldRender = currentInView.indexOf(pageNumber) > -1
    setRenderLayer(shouldRender)
  }, [currentInView,scale]);

const onRenderSuccess = async (page) => {
  ref.current!.querySelectorAll('.react-pdf__Page')?.forEach((el:HTMLElement) => {
    el.style.removeProperty('--scale-factor')
  })
  ref.current!.querySelectorAll('.react-pdf__Page__canvas')?.forEach((el:HTMLElement) => {
    el.style.width = `round(down,var(--scale-factor) * ${page.originalWidth}px,1px)`
    el.style.height = `round(down,var(--scale-factor) * ${page.originalHeight}px,1px)`
  })
  if(page.pageNumber === 1) {
    publish(ref.current as any,'gotFirstPageSize',{width:page.originalWidth,height:page.originalHeight})
  }
  if(page.pageNumber === totalNumber) {
    publish(ref.current as any,'pageRenderFinished',null)
  }
}
```

**Comment by HJZzzzz** [comment] 2025-02-25 04:13
@rsshilli hi, nice sharing!
Im wondering are there any pitfalls with this approach? Will there be any positioning issue with text/annotation layer. 
Did you test it under different cases?
