### ISSUE TITLE
PDF rendering glitches

### ISSUE THREAD

**Issue by JasoonX** [wojtekmaj/react-pdf#1273] opened 2023-01-10 10:57 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Recently (approx. last week) all of the pdfs in my personal reader started rendering with weird glitches.
![image](https://user-images.githubusercontent.com/25570307/211531550-5b513203-f6a8-44a9-bf76-246910a3efd7.png)

It worked perfectly fine for 3-5 months, and with no code changes, this started happening.

### Expected behavior

Pdf is displayed without glitches

### Actual behavior

Pdf is displayed with visual glitches

### Additional information

Tested pdf.js demo here: https://mozilla.github.io/pdf.js/web/viewer.html, file loads correctly.

### Environment

- **Browser (if applicable)**: Google Chrome
- **React-PDF version**: ^5.7.2
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment] 2023-01-11 07:50
Duplicate of #1010

**Closed by wojtekmaj** 2023-01-11 07:50 UTC
Labels: bug
