### ISSUE TITLE
Distorted text

### ISSUE THREAD

**Issue by Greg-Hitchon** [wojtekmaj/react-pdf#1025] opened 2022-07-14 20:48 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am getting a pdf that is rendered incorrectly and looks like:
![image](https://user-images.githubusercontent.com/3837138/179080844-beccc57b-2785-4227-b1e0-835b14f1916d.png)

The actual pdf looks normal.

It is not one of the overlays causing the issue (text or annotation) and when toggling back and forth between single page and multi-page views the issue resolves. It also seems dependent on the resolution or appears on some machines and not others so it is a little tricky to repro.

### Steps to reproduce

Difficult to consistently reproduce.

### Expected behavior

Display pdf clearly

### Actual behavior

Pdf is distorted

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by salahCoone** [comment] 2022-07-18 07:31
I also facing the same problem

**Comment by JaviCeRodriguez** [comment] 2022-07-19 13:27
I have the same problem with external pdf docs (Google Chrome). I use this versions deps:

- **react**: 18.1.0
- **react-dom**: 18.1.0
- **react-pdf**: 5.7.2

This is my react component for use react-pdf:
```tsx
import React, { useState } from 'react';
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import { Box } from '@mui/material';
import './index.css';

const PDFViewer: React.FC<{ fileURL: string }> = ({ fileURL }) => {
  const [numPages, setNumPages] = useState(null);

  const onDocumentLoadSuccess = (args: any) => {
    setNumPages(args.numPages);
  };

  return (
    <Document
      className="document-pdf"
      file={fileURL}
      onLoadSuccess={onDocumentLoadSuccess}
    >
      {Array.from(new Array(numPages), (el, index) => (
        <Box key={`page_${index + 1}`} marginBottom="10px">
          <Page width={900} pageNumber={index + 1} />
        </Box>
      ))}
    </Document>
  );
};

export default PDFViewer;
```

**Comment by arfanliaqat** [comment] 2022-07-20 08:19
We also faced the same issue in our app. However if we disable *Accelerated 2D canvas* in chrome://flags then the preview appears nice and okay. But since this flag is on by default so user see the pixlated preview. Unless we ask them to turn off this flag. Any resoluation is appreciated. 🙏

**Comment by michael-roberts-lwt** [comment] 2022-07-21 17:04
Looks like they found at least a temporary solution over on react-pdf/renderer. 
https://github.com/diegomura/react-pdf/issues/1890#issuecomment-1168016232
> One option is to use the renderMode="svg" on the Document but the resulting fonts are not correct.

This worked for me in react-pdf: 5.7.2, and my fonts all still look correct.

**Comment by mcgeld** [comment] 2022-09-08 22:20
> Looks like they found at least a temporary solution over on react-pdf/renderer. [diegomura/react-pdf#1890 (comment)](https://github.com/diegomura/react-pdf/issues/1890#issuecomment-1168016232)
> 
> > One option is to use the renderMode="svg" on the Document but the resulting fonts are not correct.
> 
> This worked for me in react-pdf: 5.7.2, and my fonts all still look correct.

This did help the text render correctly in my case, but then any images embedded in the pdf don't render. The images just show up as the standard 'image not found' image.

**Comment by Greg-Hitchon** [comment] 2022-10-14 11:46
> > Looks like they found at least a temporary solution over on react-pdf/renderer. [diegomura/react-pdf#1890 (comment)](https://github.com/diegomura/react-pdf/issues/1890#issuecomment-1168016232)
> > > One option is to use the renderMode="svg" on the Document but the resulting fonts are not correct.
> > 
> > 
> > This worked for me in react-pdf: 5.7.2, and my fonts all still look correct.
> 
> This did help the text render correctly in my case, but then any images embedded in the pdf don't render. The images just show up as the standard 'image not found' image.

Yeah this is the same for me...pretty funny tbh, like playing whack-a-mole with these settings. Free though so can't complain, going to investigate some paid options I guess!

**Comment by wojtekmaj** [comment] 2022-11-10 17:21
Can you still see this in v6? PDF.js got updated in v6 so chances are the issues you're experiencing have been resolved by now.

**Comment by Greg-Hitchon** [comment] 2022-11-10 18:43
I will test when I get a chance! However I am not sure this will be resolved...see [here](https://github.com/mozilla/pdf.js/issues/14641#issuecomment-1303258086)...i think this is the same issue and the pdf.js folks seem to just be not supporting chrome...

**Comment by pvg8v6g** [comment] 2022-12-01 17:45
> Can you still see this in v6? PDF.js got updated in v6 so chances are the issues you're experiencing have been resolved by now.

I can confirm this is still an issue with v6.0.3

**Comment by 1Jesper1** [comment] 2022-12-07 12:24
Problem exists in Chrome and Edge, but problem doesn't exist when using Firefox.

**Comment by 1Jesper1** [comment] 2023-01-10 09:38
https://github.com/mozilla/pdf.js/issues/14641#issuecomment-1376883244 Seems to be fixed by Chrome?

**Comment by wojtekmaj** [comment] 2023-01-11 07:51
Duplicate of #1010

**Closed** 2023-01-11 07:51 UTC
Labels: bug
