### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by hanselsen** [wojtekmaj/react-pdf#61] opened 2017-09-18 13:13 UTC
I'm experiencing memory errors on node build.  
This is only the case when react-pdf is included and used in the project.  

The command:

> node react-scripts build

The error:

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

I even added the memory argument  

> node --max-old-space-size=8192 react-scripts build

In the package.json

> "react-pdf": "^2.1.1",

Please advice

**Comment by wojtekmaj** [comment] 2017-09-19 22:25
Hey @hanselsen,
Sadly I have no knowledge about react-scripts and this looks like issue on their side. I personally use Webpack to build the project and although it takes quite a bit of time (sometimes over 2 minutes), it always finishes. Not sure what react-scripts has under the hood. Could you drop them a note, too?
Thanks,
Wojciech

**Comment by hanselsen** [comment] 2017-09-20 06:15
@wojtekmaj I use webpack too. It also takes a long time. (6 minutes in the past, but I managed to speed that up luckily). Is the React-PDF package so big that by adding it, it just claims all memory available? Or do you have no experience with this?

**Comment by wojtekmaj** [comment] 2017-09-20 06:30
@hanselsen React-PDF itself is rather tiny. Takes a couple of seconds to pack it. However its dependency, mozilla/react.pdf, is something waaaay bigger. 
Webpack had this thing called cacheDirectory, maybe this would help you?

**Comment by wojtekmaj** [comment] 2017-09-28 19:52
@hanselsen I'm closing this in effort to keep Issues page clean of issues that are no longer discussed. I will be happy to reopen in case you still have this issue!

**Closed by wojtekmaj** 2017-09-28 19:52 UTC

**Comment by ChrisHendrX** [comment] 2019-09-25 16:00
Hello, I had the same issue.
So I updated me package.json : react-scripts --max_old_space_size=4096 build
It worked out for me :)

**Comment by ChampIsMe** [comment] 2019-12-12 16:34
> I'm experiencing memory errors on node build.
> This is only the case when react-pdf is included and used in the project.
> 
> The command:
> 
> > node react-scripts build
> 
> The error:
> 
> > FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
> 
> I even added the memory argument
> 
> > node --max-old-space-size=8192 react-scripts build
> 
> In the package.json
> 
> > "react-pdf": "^2.1.1",
> 
> Please advice

I have this exact problem immediately I added react-pdf library to my project. When I comment out it's imports, everything works fine until I uncomment them. Meaning the problem is with the library. Kindly help.

**Comment by hungdev** [comment] 2020-01-03 08:42
i got same problem.

**Comment by amzick** [comment] 2020-02-07 18:05
I am also experiencing this issue.
