### ISSUE TITLE
Some PDFs not rendering correctly on Chrome 92 and up

### ISSUE THREAD

**Issue by mashaod** [wojtekmaj/react-pdf#819] opened 2021-07-28 10:33 UTC
Yesterday we updated Chrome to 92.0.4515.107 and found a broken file in our pdf viewer. We checked it again with the older Chrome version and everything is ok. It happens with a specific pdf file (I attached it below).

There are screens from our pdf viewer.
1. How it should look.
![image](https://user-images.githubusercontent.com/30415534/127301683-00e52b34-46fb-45e8-b7c7-6eb8bafb4ab6.png)

2. How it actually looks.
![image](https://user-images.githubusercontent.com/30415534/127301801-4b39cb9e-fd79-4422-b6b4-2ede3fc02be7.png)

- Load [broken_pdf_bill.pdf](https://github.com/wojtekmaj/react-pdf/files/6892265/broken_pdf_bill.pdf) file to react-pdf viewer

Expected behavior:
- Render all content correctly

**Environment**

 - Browser: Chrome Version 92.0.4515.107
 - React-PDF version: 5.2.0 / 5.4.0 / 5.3.2
 - React version: 16.14.0
 - Webpack version: 4.46.0

**Comment by wojtekmaj** [comment] 2021-07-28 12:28
Confirmed fixed by #818.

Please try v5.4.0-beta.2.

**Comment by mashaod** [comment] 2021-07-28 12:58
@wojtekmaj  I have the same issue with v5.4.0-beta.2. Sorry, but this fix doesn't work for my case.

**Comment by mashaod** [comment] 2021-07-30 09:13
@wojtekmaj I created a small example for you with a similar issue in another file. 

https://codesandbox.io/s/react-pdf-with-crome-92-ybvzv

I upload two identical files with different pdf versions.
In the first case react-pdf viewer doesn't render some fields.
If you try to open the files in a browser, they will be correct.

**Comment by AgnesFrancis** [comment] 2021-08-02 07:43
@mashaod : Can you please confirm if the issue is fixed with react-pdf version v5.4.0-beta.2 , as I am also facing the same issue.

**Comment by mashaod** [comment] 2021-08-02 07:59
@AgnesFrancis  You could check this issue example https://codesandbox.io/s/react-pdf-with-crome-92-ybvzv with v5.4.0-beta.2. This version doesn't help in my case. I guess the problem is in the file parameters.

**Comment by sorodrigo** [comment] 2021-08-06 17:28
@mashaod we fixed the issue by removing the webpack worker syntax and [going back to the standard setup](https://github.com/wojtekmaj/react-pdf#standard-browserify-and-others).

**Comment by ObaidaAlhaasan** [comment] 2021-08-12 07:14
@mashaod I had the same issue and by using version `5.3.2` it worked and the docs were rendered correctly, give it a try if you still have the issue

**Comment by mashaod** [comment] 2021-09-01 14:43
Thanks a lot. I fixed the issue with a new version of react-pdf.

**Comment by wojtekmaj** [comment] 2021-09-02 09:39
Closed in v5.4.0-beta.3

**Closed by wojtekmaj** 2021-09-02 09:39 UTC
Labels: bug
