### ISSUE TITLE
pdfjs-dist version

### ISSUE THREAD

**Issue by Amerehei** [wojtekmaj/react-pdf#1598] opened 2023-08-25 13:37 UTC
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Is there any reason that version of pdfjs-dist is limited to "3.6.172"? Can you change it to "^3.6.172"?
Or at least is it possible to update it to the latest version?

**Comment by wojtekmaj** [comment] 2023-08-25 15:47
Duplicate of #982

**Closed** 2023-08-25 15:47 UTC
Labels: enhancement
