### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jaspreetcj** [wojtekmaj/react-pdf#499] opened 2019-12-18 12:50 UTC
using
webpack 4.41.0
react-pdf 4.0.0
 as soon as I upgraded from react-pdf 3.6.0 to react-pdf 4.0.0.

npm start started throwing following error:

> react-scripts start

Starting the development server...

<--- Last few GCs --->

[15124:000000000278EB10]    85121 ms: Scavenge 1364.1 (1423.1) -> 1363.4 (1423.6) MB, 3.9 / 0.0 ms  (average mu = 0.248, current mu = 0.212) allocation failure
[15124:000000000278EB10]    85126 ms: Scavenge 1364.6 (1423.6) -> 1364.0 (1424.1) MB, 3.3 / 0.0 ms  (average mu = 0.248, current mu = 0.212) allocation failure
[15124:000000000278EB10]    85129 ms: Scavenge 1364.8 (1424.1) -> 1364.2 (1425.1) MB, 2.3 / 0.0 ms  (average mu = 0.248, current mu = 0.212) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000002F27D8DC5C1]
Security context: 0x00457089e6e1 <JSObject>
    1: SourceMapConsumer_allGeneratedPositionsFor [0000011875549E51] [C:\Intellij_Workspace\UIBranch\si-staff-view-ui\node_modules\source-map\lib\source-map-consumer.js:~178] [pc=000002F27DCF78
61](this=0x0296ab202291 <BasicSourceMapConsumer map = 000000AA492665F1>,aArgs=0x036054b82221 <Object map = 000000AA49265A99>)
    2: /* anonymous */(aka /* anonymous...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 000000013F280EFA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 000000013F25A296 node::MakeCallback+4518
 3: 000000013F25AC80 node_module_register+2160
 4: 000000013F4F09BE v8::internal::FatalProcessOutOfMemory+846
 5: 000000013F4F08EF v8::internal::FatalProcessOutOfMemory+639
 6: 000000013FA2E954 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 000000013FA250B7 v8::internal::ScavengeJob::operator=+25543
 8: 000000013FA2362C v8::internal::ScavengeJob::operator=+18748
 9: 000000013FA2C5A7 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 000000013FA2C626 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 000000013F5CF447 v8::internal::Factory::NewFillerObject+55
12: 000000013F66712A v8::internal::WasmJs::Install+29530
13: 000002F27D8DC5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! si-staff-view-ui@0.1.0 start: `react-scripts start`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the si-staff-view-ui@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by brentmitch** [comment] 2019-12-18 14:35
I think these are the same issue:

#496 

#498

**Comment by wojtekmaj** [comment] 2019-12-21 14:47
Duplicate of #496

**Closed by wojtekmaj** 2019-12-21 14:47 UTC
Labels: duplicate, question
