### ISSUE TITLE
customTextRenderer is not called with various valid PDFs

### ISSUE THREAD

**Issue by corystevens** [wojtekmaj/react-pdf#1530] opened 2023-06-08 16:19 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

After migrating from v6 to v7, the customTextRenderer function is no longer being called for our PDFs.  We use this to add document highlighting.  The issue seems to be around the TextLayer looking for `markedContent` classes, which are not present in the rendered DOM for many PDFs I've tested. 

PDF test url: https://www.soundczech.cz/temp/lorem-ipsum.pdf

This issue is also present in the test project, so its not related to our code. 

Working document with highlighting:
<img width="1064" alt="Screenshot 2023-06-08 at 8 47 54 AM" src="https://github.com/wojtekmaj/react-pdf/assets/3331233/64c4e989-3a11-4c14-82a3-8fb10578db7a">

Test document with no highlighting
<img width="1072" alt="Screenshot 2023-06-08 at 8 48 10 AM" src="https://github.com/wojtekmaj/react-pdf/assets/3331233/aa3808f9-1274-4cc3-9a97-d2d57193e8a9">

Looking at the DOM of each document, you can see slight differences in structure.

Working document:
<img width="746" alt="Screenshot 2023-06-08 at 8 49 09 AM" src="https://github.com/wojtekmaj/react-pdf/assets/3331233/d3d0a8ba-1585-4d08-b993-1932d690b1a6">

Not working document
<img width="743" alt="Screenshot 2023-06-08 at 8 48 47 AM" src="https://github.com/wojtekmaj/react-pdf/assets/3331233/796b6986-2a57-491b-b8a0-3fedf24684a5">

### Steps to reproduce

Use almost any PDF, have a customTextRenderer, see if that renderer is called.  PDFs generated with the "print to PDF" functionality in browsers will have this issue.

### Expected behavior

customTextRenderer is called for PDFs

### Actual behavior

customTextRenderer is not called for many PDFs

### Environment

- **Browser (if applicable)**:
- Chrome,Firefox
- **React-PDF version**:
- 7.1.1
- **React version**:
- 18
- **Webpack version (if applicable)**:

**Comment by MattL75** [comment] 2023-06-09 14:56
Definitely related to the struct tree layer addition. I'm guessing the issue is when you have a pdf that is not tagged, or not tagged properly.

This line `const layerChildrenDeep = layer.querySelectorAll('.markedContent > *:not(.markedContent');` would not extract tags that do not have a markedContent class as parent.

@wojtekmaj We could first check that there _are_ items with markedContent class set?

**Comment by MattL75** [comment] 2023-06-09 15:17
I will get on that

**Comment by wojtekmaj** [comment] 2023-06-12 06:02
Fixed in 7.1.2. Thanks @MattL75!

**Closed** 2023-06-12 06:01 UTC
Labels: bug
