### ISSUE TITLE
render slow for a page with >10 pictures

### ISSUE THREAD

**Issue by bfang711** [wojtekmaj/react-pdf#326] opened 2019-01-03 18:10 UTC
To render a page with many (>10) pictures, it will take 3-4 seconds to load the page. However after the page shows, if I come back to the same page, it is fast almost instant.  I wonder if there is any solution for that.  

I use react-pdf 3.0 since my REACT is 16.2.0.   I use npm and webpack.  

import { Document, Page} from 'react-pdf/dist/entry.webpack';  (this is how I import the modules.) 

FYI. I used "Performance" in Chrome to track, seems like most time wastes in rendering. 

This is how I do it. Please let me know if this is the correct way or any better way of doing it.  (I just want to show one page per screen and I have another button to control the page number prop.)  The pdf has only 22 pages, but there are more than 10 pictures per page.  

```
shouldComponentUpdate(newProps, newState)
    {
	if(newProps.pageNumber != this.props.pageNumber
	   || newProps.numPages != this.props.numPages)
	    return true;
	return false;
    }

pdfOnLoadSuccess(pdf)
    {
	console.log(pdf);
	this.props.dispatch(reportActions.set_total_pages(pdf.numPages));
    }
    
render()
{
<Document
        file={{url:this.props.URL}}
	 onLoadSuccess={this.pdfOnLoadSuccess}>
	 <Page 
               pageIndex={this.props.pageNumber} //this.props.pageNumber controlled by a button.
               onLoadSuccess={(page)=>{console.log("Loaded page "+this.props.pageNumber);}}  
               onRenderSuccess={(page)=>{console.log("Rendered page "+this.props.pageNumber);}}
	   />
 </Document>
}
```

From the console log, I can see that onLoadSuccess of <Page> was called almost right after the page number gets changed. However 3 seconds later, onRenderSuccess of <Page> got called. Why it takes such a long time to render the page? 

Please let me know how to resolve the issue.

Thank you.

**Comment by wojtekmaj** [comment] 2019-01-04 08:35
Well, the package does exactly what it was order to, which in this case is rendering 10 pages at once. This will never end well. Please see #94 for more info.

**Comment by wojtekmaj** [comment] 2019-01-04 08:35
Duplicate of #94

**Closed by wojtekmaj** 2019-01-04 08:35 UTC
