### ISSUE TITLE
Issues with webpack build after upgrading from 5.2.0 to 5.3.2

### ISSUE THREAD

**Issue by coolbeans47** [wojtekmaj/react-pdf#821] opened 2021-07-29 09:57 UTC
Everything was running great with 5.2.0 but I get problems after upgrading to 5.3.2. My create-react-app application runs fine with 5.3.2 after the upgrade using "npm start", but when I build the application and serve from the build folder I get problems loading a PDF. I am importing **Document** and **Page** using the webpack instructions. The browser console shows:

**606f8871e58467aeb728b7eb0c45aa77.js:2 Uncaught ReferenceError: require is not defined**

I am importing document and page like this:

import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';

I have also tried to use the umd imports but I get the same problem.

Downgrading to 5.2.0 works fine. 

Please help.

**Comment by wojtekmaj** [comment] 2021-07-29 10:35
Duplicate of #782

**Closed by wojtekmaj** 2021-07-29 10:35 UTC
