### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' (at pdf.worker.js:1:1)

### ISSUE THREAD

**Issue by rd7r7** [wojtekmaj/react-pdf#991] opened 2022-04-19 01:09 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

hello
I am using `react-pdf` `version 5.x` in my react **`version 18`** app and it throws me the following error
Warning: Setting up fake worker.
Uncaught SyntaxError: Unexpected token '<' (at pdf.worker.js:1:1)
![Captura1](https://user-images.githubusercontent.com/102402314/163899939-99e714ea-561a-43d3-a24e-b20fa54b0312.JPG)

### Steps to reproduce

****

### Expected behavior

****

### Actual behavior

****

### Additional information

****

### Environment

- **Browser (if applicable)**:
- **React-PDF v 5.x**:
- **React v18**:
- **Webpack version (if applicable)**:
![Captura1](https://user-images.githubusercontent.com/102402314/163900301-6404da4c-0d5e-4fb0-8815-b9b9742d63d7.JPG)

**Comment by wojtekmaj** [comment] 2022-04-19 08:24
Duplicate of #97
See also #680 and [others](https://github.com/wojtekmaj/react-pdf/issues?q=Uncaught+SyntaxError%3A+Unexpected+token+%27%3C).

**Closed by wojtekmaj** 2022-04-19 08:24 UTC
Labels: duplicate, question

**Comment by luciano1997** [comment] 2022-05-04 20:28
import { Document, Page, pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
this work for me

dependences 
"react-pdf": "^5.7.2",

**Comment by matrolat** [comment] 2022-12-11 05:58
Import 
`import { Document, Page, pdfjs } from "react-pdf";`

Also add this inside your functional component
`  useEffect(() => { 
    pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;    
  });`

**Comment by sanjar-162** [comment] 2024-09-04 09:12
> Import `import { Document, Page, pdfjs } from "react-pdf";`
> 
> Also add this inside your functional component ` useEffect(() => { pdfjs.GlobalWorkerOptions.workerSrc =`[https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;}](https://cdnjs.cloudflare.com/ajax/libs/pdf.js/$%7Bpdfjs.version%7D/pdf.worker.js%60;%7D));
> 
> `

?
