### ISSUE TITLE
in version 2.5.3 page.width/ page.scale does not work together

### ISSUE THREAD

**Issue by yanivkalfa** [wojtekmaj/react-pdf#324] opened 2019-01-01 00:58 UTC
in version 2.5.3 page.width/ page.scale does not work together
Like mentioned in the docs: https://github.com/wojtekmaj/react-pdf/blob/v2.x/README.md#props-1

scale will work perfectly fine when width is not set, however when width is set it takes priority over scale

**Comment by wojtekmaj** [comment] 2019-01-02 10:53
Hi,
if the problem exists in 3.x/4x I could make a fix, but 2.x is no longer supported.

**Comment by wojtekmaj** [comment] 2019-01-05 10:36
Confirmed, fixed in 4.x. Possibly will also do 3.x fix, but as I said 2.x is not supported anymore. Thanks!

**Closed by wojtekmaj** 2019-01-05 10:36 UTC

**Comment by wojtekmaj** [comment] 2019-01-05 10:38
Duplicate of #322
