### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'sendWithPromise')

### ISSUE THREAD

**Issue by FedeMadoery** [wojtekmaj/react-pdf#1473] opened 2023-04-28 19:43 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I'm using React-PDF inside an insolated view that just receives the file URL, that view is wrapped in a <Suspense/> because I'm using SWR to fetch that file URL. The PDF is rendered as expected the first time, but when a new item is selected and the Suspense is triggered again by the query when the Suspense ends I face this issue, I tried rendering it in a condition way, and the error persist. 

### Steps to reproduce

I will work on an easy to reproduce code-sandbox.

### Expected behavior

Load and render the new PDF based on the url.

### Actual behavior

Throw an error `Error: Cannot read properties of null (reading 'sendWithPromise')`

### Additional information

Full stack trace:

```
Error: Cannot read properties of null (reading 'sendWithPromise')
    at WorkerTransport.getPage (pdf.js:3109:1)
    at PDFDocumentProxy.getPage (pdf.js:1566:1)
    at PageInternal.eval [as loadPage] (Page.js:75:40)
    at PageInternal.componentDidMount (Page.js:92:1)
    at safelyCallComponentDidMount (react-dom.development.js:22882:1)
    at reappearLayoutEffectsOnFiber (react-dom.development.js:23536:1)
    at reappearLayoutEffects_complete (react-dom.development.js:24838:1)
    at reappearLayoutEffects_begin (react-dom.development.js:24826:1)
    at commitLayoutEffects_begin (react-dom.development.js:24649:1)
    at commitLayoutEffects_begin (react-dom.development.js:24656:1)
    at commitLayoutEffects_begin (react-dom.development.js:24656:1)
    at commitLayoutEffects_begin (react-dom.development.js:24656:1)
    at commitLayoutEffects_begin (react-dom.development.js:24656:1)
    at commitLayoutEffects_begin (react-dom.development.js:24656:1)
    at commitLayoutEffects_begin (react-dom.development.js:24656:1)
    at commitLayoutEffects_begin (react-dom.development.js:24656:1)
    at commitLayoutEffects_begin (react-dom.development.js:24656:1)
    at commitLayoutEffects (react-dom.development.js:24612:1)
    at commitRootImpl (react-dom.development.js:26823:1)
    at commitRoot (react-dom.development.js:26682:1)
    at finishConcurrentRender (react-dom.development.js:25981:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25809:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1) {c
```

### Environment

- **Browser (if applicable)**: Chrome / Brave
- **React-PDF version**: 6.2.2
- **React version**: 18.2.0
- **NextJs version**: 13.1.1
- **Webpack version (if applicable)**:

**Comment by KalanaPerera** [comment] 2023-04-30 02:13
got same error +1

**Comment by joshuaward** [comment] 2023-05-01 14:46
I'm also getting the same error.

**Comment by Tohix** [comment] 2023-05-05 11:12
+1

**Comment by happylolonly** [comment] 2023-05-16 12:13
having the same in 7.0.0 version, not possible to use lib

**Comment by wojtekmaj** [comment] 2023-05-18 18:01
Duplicate of #974 974

**Closed by wojtekmaj** 2023-05-18 18:01 UTC
Labels: bug

**Comment by petr-brabec-cu** [comment] 2023-06-16 13:24
Are you sure it's a duplicate @wojtekmaj? This one has a different stack trace (same as mine).

**Comment by wojtekmaj** [comment] 2023-06-16 13:29
Yes. Yours has a better stacktrace, your tooling was configured better indeed, but it's the same error.

**Comment by TJohn2017** [comment] 2023-12-09 01:44
@soltanireza65 Thank you for sharing! This worked for us. Could you explain why hosting it through the public folder solves this?

**Comment by huypham1411** [comment] 2023-12-22 03:48
> ## Solution:
> * Upgrade react-pdf from 6 to 7
> * Copy `react-pdf/node_modules/pdfjs-dist/build/pdf.worker.js` to `public`
> * Notice that worker is inside `react-pdf/node_modules` and not in the root level node_modules

Hi, I cannot find the react-pdf/node_modules, I'm using NextJS so hope you can guide me, appreciate

**Comment by ZhihaoWan** [comment] 2024-03-01 22:37
> ## Solution:
> * Upgrade react-pdf from 6 to 7
> * Copy `react-pdf/node_modules/pdfjs-dist/build/pdf.worker.js` to `public`
> * Notice that worker is inside `react-pdf/node_modules` and not in the root level node_modules

Thanks at first, while I only found there is only `pdf.worker.mjs` rather than `pdf.worker.js`, are they same??

**Comment by alexis2m** [comment] 2024-03-27 21:34
> > ## Solution:
> > 
> > * Upgrade react-pdf from 6 to 7
> > * Copy `react-pdf/node_modules/pdfjs-dist/build/pdf.worker.js` to `public`
> > * Notice that worker is inside `react-pdf/node_modules` and not in the root level node_modules
> 
> Hi, I cannot find the react-pdf/node_modules, I'm using NextJS so hope you can guide me, appreciate

Hi,

It's inside `nodes_modules/react-pdf/nodes_modules/pdfjs-dist/build`

**Comment by fsogutcen** [comment] 2024-08-05 12:00
Hi, I am using ReactJS. I have react-pdf and pdfjs-dist in root level node_modules. But I can't find react-pdf/node_modules/pdfjs-dist.
I have pdfjs-dist/build/pdf.worker in root level. Should I move this one to public?

**Comment by johnnyshankman** [comment] 2024-11-04 19:26
I'm having this error in `"react-pdf": "^9.1.1",`

**Comment by johnnyshankman** [comment] 2024-11-04 19:54
Fixed following solve here: https://github.com/wojtekmaj/react-pdf/issues/974
