### ISSUE TITLE
For some reason cMapUrl isn't calling CDN request

### ISSUE THREAD

**Issue by justice-art** [wojtekmaj/react-pdf#623] opened 2020-08-05 10:18 UTC
Hi there ! Document props:
```
<Document
  file={pdfURL}
  onLoadSuccess={onDocumentLoadSuccess}
  options={{
    cMapUrl: `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`, 
    cMapPacked: true,
  }}
>`
```

Also I use CDN for worker code: ``pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;``  (This code works)

BTW: I've tried do this via webpack solution. It also doesn't work.

Thanks in advance !

**Comment by DavidBuzatu-Marian** [comment] 2020-08-10 10:53
I am dealing with the same problem (the same set-up with worker code and external cMap). Did you find a workaround?

**Comment by omerz-suridata** [comment] 2021-12-06 10:23
I'm experiencing the same issue, 
**react-pdf version:** `"react-pdf": "^5.5.0"`
**react version:** `"react": "^16.14.0"`

I'm loading the cMaps like so:
```
<Document
        renderMode="canvas"
        file={file}
        options={{
          cMapURL: `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`,
          cMapPacked: true,
        }}>
```

My network window - 
![image](https://user-images.githubusercontent.com/87695156/144829611-36282e31-d2a9-4b89-a38e-a9e9975aa391.png)

Any ideas? @wojtekmaj

**Comment by ckc2715** [comment] 2022-01-28 07:49
I have experienced same issue and fixed with a absolute cMapUrl.
 
```
<Document
        renderMode="canvas"
        file={file}
        options={{
            options={{
                cMapUrl: `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`,
                cMapPacked: true,
            }}
>
```

**Comment by wojtekmaj** [comment] 2022-01-28 22:00
You need to remember that not always cMaps will be needed, so they may not be fetched at all. If you think they should though, I'm more than happy to look at a repro repo that shows this unexpected behavior. So far, I couldn't reproduce on my own.

**Comment by ckc2715** [comment] 2022-01-29 15:41
> You need to remember that not always cMaps will be needed, so they may not be fetched at all. If you think they should though, I'm more than happy to look at a repro repo that shows this unexpected behavior. So far, I couldn't reproduce on my own.

Foy my case, it is reproduced here: [https://codesandbox.io/s/crimson-dawn-q41fd?file=/src/App.js](url)

The error from console:
`Warning: Error during font loading: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from //cdn.jsdelivr.net/npm/pdfjs-dist@2.12.313/cmaps/Adobe-Japan1-UCS2.bcmap`

As I mentioned above, simply use absolute path can solve this issue.
Please consider update the document if it makes sense. 
Thank you.

**Comment by wojtekmaj** [comment] 2022-01-29 21:35
Oh, you're absolutely right - updated! Thank you @ckc2715!

**Closed** 2022-01-29 21:36 UTC
Labels: question
