### ISSUE TITLE
How to get the number of pages?

### ISSUE THREAD

**Issue by clement-estone** [wojtekmaj/react-pdf#1277] opened 2023-01-13 09:24 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The example provided in the README:

```typescriptreact
import React, { useState } from 'react';
import { Document, Page } from 'react-pdf';

function MyApp() {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return (
    <div>
      <Document file="somefile.pdf" onLoadSuccess={onDocumentLoadSuccess}>
        <Page pageNumber={pageNumber} />
      </Document>
      <p>
        Page {pageNumber} of {numPages}
      </p>
    </div>
  );
}
```

Does not work, as `numPages` is undefined. It is also not present in the types definition.

How can I get the total number of pages in the PDF?

Thanks in advance for your help!

### Steps to reproduce

N/A

### Expected behavior

`numPages` should be present in the callback's object

### Actual behavior

`numPages` is `undefined`, and also not part of the type signature

### Environment

`react-pdf`: `5.7.2`, also tried with `6.2.2`

**Comment by clement-estone** [comment] 2023-01-13 14:14
After checking, some of the examples in the `samples` directory do not work anymore either.

**Comment by clement-estone** [comment] 2023-01-17 14:05
Up! Does anyone knows how to do that? I really need this for an important feature, so I'm quite in a hurry...

I tried to inspect the code but the number of pages seems to only be available internally.

**Comment by v3gard** [comment] 2023-01-18 07:36
I also use version 5.7.2 for a project as the newer versions has [this](https://github.com/wojtekmaj/react-pdf/issues/1292) bug. For your issue however, this seems to do the trick for me at least. 

1. Initialize numPages to `0` instead of `null`), and
2. Use an anonymous function for the `onLoadSuccess` callback.

`downloadUrl` is a special URL to a blob that that has already been downloaded using an HTTP client like `fetch` or `axios`, and passed to `<Document/>` via `window.URL.createObjectURL(responseBlob)`. `responseBlob` is a `Blob` datatype containing all the raw bytes of the PDF.

```ts
const [numPages, setNumPages] = useState(0);
...
<Document
    onLoadError={console.error}
    file={downloadUrl}
    onLoadSuccess={({ numPages: numPagesInPdf }) => {
        setNumPages(numPagesInPdf);
    }}
    loading={loadingText}
>
```

**Comment by clement-estone** [comment] 2023-01-18 08:59
That worked! Thanks for your help :)

**Comment by wojtekmaj** [comment] 2023-02-10 10:39
I can assure you getting numPages work :) Here's a full example:
https://codesandbox.io/p/sandbox/react-pdf-pagination-usz4km

PS. #1292 is not a bug and has been already resolved by the community so it might be worth checking out v6.

**Closed by wojtekmaj** 2023-02-10 10:39 UTC
Labels: bug
