### ISSUE TITLE
TypeError: Promise.withResolvers is not a function

### ISSUE THREAD

**Issue by muscaiu** [wojtekmaj/react-pdf#1831] opened 2024-06-18 13:41 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Tried to implement this library in NExtJS for a few hours now, but can't get rid of this error.

Also used your Sample next-app and still same error.

<img width="832" alt="Screenshot 2024-06-18 at 16 37 21" src="https://github.com/wojtekmaj/react-pdf/assets/11426309/bedd7621-14da-4110-a3b3-661311fdeac2">

### Steps to reproduce

Use your Sample Next-App, install dependencies and run dev.
In my case yarn wasn't working so i used pnpm.

### Expected behavior

no error

### Actual behavior

TypeError: Promise.withResolvers is not a function

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Bundler name and version (if applicable)**:

**Comment by wontory** [comment] 2024-06-18 23:00
I am also experiencing the same issue

**Comment by LaurentDelteil** [comment] 2024-06-19 09:18
Can this function be rewritten to be compatible with Chrome versions earlier than 119, such as those used on Windows 8, or Safari 17.4, which was released three months ago?

**Comment by wojtekmaj** [comment] 2024-06-19 09:58
Duplicate of #1811

**Closed** 2024-06-19 09:58 UTC
Labels: bug

**Comment by aldwnesx** [comment] 2024-07-07 13:25
> Duplicate of #1811

what is the proper working solution?

**Comment by sovetski** [comment] 2025-02-04 10:58
Same problem here with the latest version

**Comment by andyfelder16** [comment] 2025-02-18 13:20
After researching similar issues, I found a working solution for Next.js. This approach resolves the `Promise.withResolvers` error by ensuring react-pdf is only loaded on the client side:

```
"use client";

import { Spinner } from "@phosphor-icons/react/dist/ssr";
import type * as ReactPdfType from "react-pdf";
import "react-pdf/dist/Page/AnnotationLayer.css";
import "react-pdf/dist/Page/TextLayer.css";

// Dynamically import react-pdf only on client side
let ReactPDF: typeof ReactPdfType | undefined;
if (typeof window !== "undefined") {
  ReactPDF = require("react-pdf");
}

// Configure worker
if (ReactPDF?.pdfjs && typeof window !== "undefined") {
  const workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${ReactPDF.pdfjs.version}/pdf.worker.min.mjs`;
  ReactPDF.pdfjs.GlobalWorkerOptions.workerSrc = workerSrc;
}

export const PDFViewer = ({ url }: { url: string }) => {
  if (!ReactPDF) {
    return (
      <div className="flex h-full min-h-[800px] w-full min-w-[600px] items-center justify-center">
        <Spinner className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  const { Document, Page } = ReactPDF;

  return (
    <Document
      file={url}
      className="bg-background/50 rounded-lg backdrop-blur-sm"
      loading={
        <div className="flex h-full min-h-[800px] w-full min-w-[600px] items-center justify-center">
          <Spinner className="h-8 w-8 animate-spin" />
        </div>
      }
    >
      <Page pageNumber={1} className="!cursor-default" />
    </Document>
  );
};

```

**Comment by kainbryanjones** [comment] 2025-04-09 07:52
Just use a polyfill

As per the spec https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers#description

```javascript
window.Promise.withResolvers = function () {
let resolve, reject;
const promise = new Promise((res, rej) => {
  resolve = res;
  reject = rej;
});
return {resolve, reject, promise}
}
```

**Comment by ryanmlow** [comment] 2025-11-10 09:06
For me I encountered this error while running unit tests covering a component making use of react-pdf components like `Document` and `Page`. In that case I resolved it by passing a mock in the test file

```
jest.mock(‘react-pdf’, () => ({
  pdfjs: {
     GlobalWorkerOptions: { workerSrc: '' }
  }
}))
```
