### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by 2208Abhinav** [wojtekmaj/react-pdf#415] opened 2019-06-22 10:52 UTC
`./node_modules/pdfjs-dist/build/pdf.js  | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

I get the above error on `npm start`
I installed react-pdf as mentioned in the docs.
```
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-router-dom": "^5.0.0",
"react-scripts": "2.1.8"
```
above is the structure of package.json and I installed react-pdf version 4.1.0

I used `create-react-app` to make the app.

**Comment by 2208Abhinav** [comment] 2019-06-22 11:08
By doing `pdfjs.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.1.266/pdf.worker.js";` I have managed to display the pdf but still the warning is occuring.

**Comment by fippli** [comment] 2019-07-02 10:10
I got the same problem when installing according to **README**. I also created the app with `create-react-app`

**Comment by anuveyatsu** [comment] 2019-07-03 08:42
Same here

**Comment by Strandol** [comment] 2019-07-03 12:03
Copy of - https://github.com/wojtekmaj/react-pdf/issues/280

**Comment by wojtekmaj** [comment] 2019-09-15 13:53
Duplicate of #280

**Closed by wojtekmaj** 2019-09-15 13:53 UTC
Labels: duplicate, question

**Comment by BenOron** [comment] 2020-05-26 15:51
My full workaround.
Create a file at the root called config-overrides.js and it should contain the following: 
module.exports = function override(config) {
     config.module.rules[0].parser.requireEnsure = true
    return config
};

After that npm i **react-app-rewired** to you app and change your build function in package.json to read react-app-rewired build/react-app-rewired start. 
That should do it for now.

**Comment by wojtekmaj** [comment] 2020-08-04 20:07
To anyone watching this thread instead of #280: See https://github.com/wojtekmaj/react-pdf/issues/280#issuecomment-641590816.

**Comment by PhilipBeauford** [comment] 2020-12-06 16:26
> react-app-rewired build/react-app-rewired start

This did absolutely nothing for me and is also badly worded. Did anyone get this fix to work?
