### ISSUE TITLE
How do you make the pdf files change in size depending on the container size?

### ISSUE THREAD

**Issue by nbhector** [wojtekmaj/react-pdf#810] opened 2021-07-15 15:42 UTC
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I am trying to display multiple pages in a container, as well as have the page adapt to the size of the container.  The pdfs render, but not completely.  It doesn't adapt to the size of the container and some pages are either missing or stacked on top of each other.   

Another issue I experienced is that when I import { Document, Page } from 'react-pdf' instead of 
'"react-pdf/dist/esm/entry.webpack"',  the application tells me that the pdf file failed to load.  I even followed the tutorials from react-pdf, but didn't work out for me.

**Describe solutions you've tried**

Here is a snippet of the code that I tried implementing: https://gist.github.com/nbhector/19347f98968582f3dd730973be423618

**Environment**

 - Browser: Brave:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 17]:

**Comment by malwilley** [comment] 2021-07-20 16:06
You will need to define `width` on the `<Page />` component. As specified in the readme:

> Page width. If neither height nor width are defined, page will be rendered at the size defined in PDF. If you define width and height at the same time, height will be ignored. If you define width and scale at the same time, the width will be multiplied by a given factor.

**Comment by Sam-CellarDoor** [comment] 2021-07-22 17:27
As far as I can tell, Page does not handle percentage widths. To get around this, you can define a className on <Page /> with a css class selector that references `.react-pdf__Page__canvas`

**Comment by wojtekmaj** [comment] 2021-07-27 11:11
Duplicate of #129

**Closed by wojtekmaj** 2021-07-27 11:11 UTC
