### ISSUE TITLE
TextLayer.css file is not updated

### ISSUE THREAD

**Issue by hrachqyutukyan** [wojtekmaj/react-pdf#1833] opened 2024-06-21 11:34 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

There is new canvas element added in v9.0.0 which has class 'hiddenCanvasElement', but there is not  'hiddenCanvasElement' class in  file /dist/Page/TextLayer.css. (you have added this class in this file in your repo files).

### Steps to reproduce

open react-pdf in node modules.

go to 
dist/cjs/Page/TextLayer.css 

search hiddenCanvasElement

### Expected behavior

It must be hiddenCanvasElement in TextLayer.css 

### Actual behavior

There is not hiddenCanvasElement in TextLayer.css 

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 9.0.0
- **React version**:18.2.0

**Comment by obecker** [comment] 2024-08-11 17:36
I guess this a duplicate of #1815 which has been resolved by commit https://github.com/wojtekmaj/react-pdf/commit/e382372427b54926a2907838dc8dfcdaf5ab3ae4

**Closed** 2024-10-24 11:54 UTC
Labels: bug
