### ISSUE TITLE
Gatsby Build Error in React PDF 5.2.0

### ISSUE THREAD

**Issue by abdurahman** [wojtekmaj/react-pdf#743] opened 2021-03-15 05:27 UTC
**Before you start - checklist**

 - [-] I have read documentation in README
 - [-] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [-] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I would like to get my application to successfully build onto my github pages repo.

**Describe solutions you've tried**

I have already tried deleting and reimporting my code from another repo to try to deploy it again and I have searched up a similar problem on the gatsby repo and on google to no avail.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

The reason I believe it has to do with react-pdf is because in the error log, it shows that the error is contained where I was using react-pdf to show pdfs on my portfolio but once I have located that I don't really know what to do afterwards and I have looked at gatsby's link on how to fix it but I have no idea on where to place the code snippet provided on the site. Wherever I placed the code snippet it just gave me more errors.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Firefox 86.0.1
 - React-PDF version [e.g. 3.0.4]: 5.2.0
 - React version [e.g. 16.3.0]: 16.14.0
 - Webpack version (if applicable) [e.g. 4.16.2]:
 - Gatsby 2.27.0

**Error Log**
success open and validate gatsby-configs - 0.010s
success load plugins - 0.919s
success onPreInit - 0.013s
success delete html and css files from previous builds - 0.002s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.
success initialize cache - 0.015s
success copy gatsby files - 0.026s
success onPreBootstrap - 0.009s
success createSchemaCustomization - 0.006s
success Checking for changed pages - 0.000s
success source and transform nodes - 0.072s
success building schema - 0.145s
info Total nodes: 69, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.000s
success Checking for changed pages - 0.000s
success createPagesStatefully - 0.022s
success Cleaning up stale page-data - 0.001s
success update schema - 0.011s
success onPreExtractQueries - 0.000s
success extract queries from components - 0.196s
success write out redirect data - 0.025s
success Build manifest and related icons - 0.133s
success onPostBootstrap - 0.134s
info bootstrap finished - 3.675s
success run static queries - 0.009s - 1/1 115.14/s
success run page queries - 0.004s - 3/3 796.13/s
success write out requires - 0.002s
success Building production JavaScript and CSS bundles - 8.392s
success Rewriting compilation hashes - 0.001s
/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17523
  window.requestAnimationFrame(resolve);
  ^

ReferenceError: window is not defined
    at /Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17523:3
    at new Promise (<anonymous>)
    at Object../node_modules/pdfjs-dist/lib/web/ui_utils.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17522:26)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Object../node_modules/pdfjs-dist/lib/web/pdf_link_service.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:16524:17)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/LinkService.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:18801:93)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/Document.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:18237:71)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/entry.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:21254:67)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../src/components/PDFResumeReader.jsx (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:22707:67)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../src/components/info.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:22818:74)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17523
  window.requestAnimationFrame(resolve);
  ^

ReferenceError: window is not defined
    at /Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17523:3
    at new Promise (<anonymous>)
    at Object../node_modules/pdfjs-dist/lib/web/ui_utils.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17522:26)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Object../node_modules/pdfjs-dist/lib/web/pdf_link_service.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:16524:17)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/LinkService.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:18801:93)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/Document.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:18237:71)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/entry.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:21254:67)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../src/components/PDFResumeReader.jsx (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:22707:67)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../src/components/info.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:22818:74)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17523
  window.requestAnimationFrame(resolve);
  ^

ReferenceError: window is not defined
    at /Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17523:3
    at new Promise (<anonymous>)
    at Object../node_modules/pdfjs-dist/lib/web/ui_utils.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17522:26)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Object../node_modules/pdfjs-dist/lib/web/pdf_link_service.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:16524:17)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/LinkService.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:18801:93)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/Document.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:18237:71)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/entry.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:21254:67)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../src/components/PDFResumeReader.jsx (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:22707:67)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../src/components/info.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:22818:74)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17523
  window.requestAnimationFrame(resolve);
  ^

ReferenceError: window is not defined
    at /Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17523:3
    at new Promise (<anonymous>)
    at Object../node_modules/pdfjs-dist/lib/web/ui_utils.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:17522:26)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Object../node_modules/pdfjs-dist/lib/web/pdf_link_service.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:16524:17)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/LinkService.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:18801:93)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/Document.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:18237:71)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../node_modules/react-pdf/dist/esm/entry.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:21254:67)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../src/components/PDFResumeReader.jsx (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:22707:67)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
    at Module../src/components/info.js (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:22818:74)
    at __webpack_require__ (/Users/abdurahman/Desktop/Semester6/repos/abdurahman.github.io/public/render-page.js:30:30)
failed Building static HTML for pages - 1.587s
error Building static HTML failed

  Error: Call retries were exceeded
  
  - ChildProcessWorker.js:193 ChildProcessWorker.initialize
    [abdurahman.github.io]/[jest-worker]/build/workers/ChildProcessWorker.js:193:21
  
  - ChildProcessWorker.js:263 ChildProcessWorker.onExit
    [abdurahman.github.io]/[jest-worker]/build/workers/ChildProcessWorker.js:263:12
  
  - node:events:378 ChildProcess.emit
    node:events:378:20
  
  - child_process:290 Process.ChildProcess._handle.onexit
    node:internal/child_process:290:12

**Comment by wojtekmaj** [comment] 2021-03-15 12:58
Duplicate of #657

**Closed by wojtekmaj** 2021-03-15 12:58 UTC
