### ISSUE TITLE
Reloading the document on every prop change

### ISSUE THREAD

**Issue by sarneeh** [wojtekmaj/react-pdf#383] opened 2019-04-04 10:45 UTC
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

`<Document />` reloads the document on every prop change when you're passing an object to the `file` prop. 

**Steps to reproduce**

Pass an object to `file` prop.

**Expected behavior**

In the code below, the `file` check should consider being an `object`, which in most cases will be everytime something new, as `{} !== {}`.

https://github.com/wojtekmaj/react-pdf/blob/2acb1a8eb662e494c49561c08b91206f4f992f2a/src/Document.jsx#L72-L77

**Environment**

 - React-PDF: 4.0.5
 - React: 16.8.6

**Comment by sarneeh** [comment] 2019-04-04 10:49
The workaround is to:

Instead of:
`<Document file={{ url: '/name.pdf', withCredentials: true }} />`
do:
`<Document file="/name.pdf" options={{ withCredentials: true }} />`

**Comment by wojtekmaj** [comment] 2019-04-08 11:45
Duplicate of #308

**Closed by wojtekmaj** 2019-04-08 11:45 UTC

**Comment by sarneeh** [comment] 2019-04-09 08:19
@wojtekmaj Oeps, sorry, I missed it :cry:

**Comment by pavan-singh-iphtech** [comment] 2024-07-09 13:23
> The workaround is to:
> 
> Instead of: `<Document file={{ url: '/name.pdf', withCredentials: true }} />` do: `<Document file="/name.pdf" options={{ withCredentials: true }} />`

not work in case of re ordering pdf
