### ISSUE TITLE
Unable to load URL

### ISSUE THREAD

**Issue by splnlss** [wojtekmaj/react-pdf#407] opened 2019-06-06 20:27 UTC
**Description**

Unable to load URL from S3 bucket. I have  installed test code and it works like a charm with local files. The URL downloads in browser as normal, but not when url is loaded in react-pdf test code.

**Steps to reproduce**

1. Run React-PDF example code 
2. Load local file.
3. Swap out local file for URL,   file = {{url: urlAddress}}

**Expected behavior**

What you expected to happen?
1. Remote Document should load, as in local behavior

**Additional information**
1) In addition, I set and double checked the CORS policy on the bucket. 
```
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Content-Type</AllowedHeader>
    <AllowedHeader>x-amz-acl</AllowedHeader>
    <AllowedHeader>origin</AllowedHeader>
    <AllowedHeader>DNT</AllowedHeader>
    <AllowedHeader>Referer</AllowedHeader>
    <AllowedHeader>User-Agent</AllowedHeader>
</CORSRule>
```

2) I ran a get test on test-cors.org which succeeds as expected, to make sure it is not missing a policy.
3) I also setup a local reference for site as mysite.local, to eliminate link to "localhost" reserved name.

Chrome:
<img width="1098" alt="Screen Shot 2019-06-06 at 4 18 22 PM" src="https://user-images.githubusercontent.com/342381/59064250-e2426a80-8877-11e9-83e6-c1f1bae67291.png">

different error in FF.
<img width="1051" alt="Screen Shot 2019-06-06 at 8 18 36 PM" src="https://user-images.githubusercontent.com/342381/59074175-5c82e700-8898-11e9-9280-bbbe76fe126c.png">

THANKS!
**Environment**

 - Browser (if) [Chrome 74, FireFox 67]:
 - React-PDF version [4.0.5]:
 - React version [16.8.6]:
 - Webpack version (if applicable) [4.29.6]:

**Comment by wojtekmaj** [comment] 2019-06-12 16:28
Duplicate of #399

**Closed by wojtekmaj** 2019-06-12 16:28 UTC
