### ISSUE TITLE
TypeScript supports

### ISSUE THREAD

**Issue by shinriyo** [wojtekmaj/react-pdf#226] opened 2018-06-14 01:44 UTC
`npm install @types/react-pdf`

but..

```
npm ERR! code E404
npm ERR! 404 Not Found: @types/react-pdf@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myname/.npm/_logs/2018-06-14T01_42_32_929Z-debug.log
```

I want to support for TypeScript 👍

**Comment by wojtekmaj** [comment] 2018-06-14 14:31
Hello there,
I'm afraid you'd have to file an issue against DefinitelyTyped, which owns @types/xxxxxxx :)

**Comment by wojtekmaj** [comment] 2018-06-14 14:32
...or better yet, you could add index.t.js to this repo as a Pull Request!

**Comment by wahlforss** [comment] 2018-11-06 16:16
What happend with this?

**Comment by wojtekmaj** [comment] 2018-11-08 16:44
Absolutely nothing I suppose :( PRs welcome.

**Comment by wojtekmaj** [comment] 2018-12-02 16:35
Duplicate of #51

**Closed by wojtekmaj** 2018-12-02 16:35 UTC
Labels: enhancement, help wanted, question
