### ISSUE TITLE
React-scripts: Critical dependency

### ISSUE THREAD

**Issue by Yooooomi** [wojtekmaj/react-pdf#255] opened 2018-08-14 13:37 UTC
Hello, I'm trying your awesome React component but react-scripts keeps telling me that.

I just installed it by 'npm i --save react-pdf' and got this error instantly in my client. Am I doing something wrong ? 

Thank you in advance

```
./node_modules/pdfjs-dist/lib/display/api.js
109:4-11 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
3882:21-28 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
3883:12-19 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
3887:60-67 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
3897:10-17 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/lib/display/api.js
94:15-22 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/lib/display/api.js
95:6-13 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/lib/display/api.js
99:54-61 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by wojtekmaj** [comment] 2018-08-14 13:50
Duplicate of #249, closing. You can update the existing issue with more details. Perhaps you're using Webpack 4 under the hood which is not yet supported?

**Closed by wojtekmaj** 2018-08-14 13:50 UTC

**Comment by williamfsilva** [comment] 2018-10-25 19:13
@wojtekmaj Is there any plans to support Webpack 4?

**Comment by aabarbosa** [comment] 2018-10-28 21:05
Not using webpack I got the same error. Probably a warning from React scripts. I updated the version of Babel, but the message prompts again. The misfortune is that PDF stops into Loading. 

The dev dependencies I tried the following. First with babel, and I expected the react script to use webpack, but the **Compiled with warnings.** remains. Eight times the message repeats

> 
> ./node_modules/pdfjs-dist/build/pdf.js
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
> 
> ./node_modules/pdfjs-dist/lib/display/api.js
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

```
> `  "devDependencies": {
>     "@babel/core": "^7.1.0",
>     "@babel/plugin-proposal-class-properties": "^7.1.0",
>     "@babel/plugin-transform-runtime": "^7.1.0",
>     "@babel/preset-env": "^7.1.0",
>     "@babel/preset-react": "^7.0.0",
>     "babel-preset-env": "^1.7.0",
>     "babel-preset-es2015": "^6.24.1",
>     "babel-preset-react": "^6.24.1",
>     "babel-loader": "^8.0.2",
>     "parcel-bundler": "^1.10.3",
>     "copy-webpack-plugin": "^4.5.2",
>     "css-loader": "^1.0.0",
>     "file-loader": "^2.0.0",
>     "style-loader": "^0.23.0",
>     "url-loader": "^1.1.1",
>     "webpack": "^4.20.2",
>     "webpack-cli": "^3.1.1"
>   }`

```

I believed that the problem was with Babel not supporting the compiling process for the react-pdf classes or it's not preconfigured or supported by react scripts.
Finally, I tried parcel and my project has 2 .html files. I got an error from the compiler using the linker.

`<script src="../src/index.js"></script>`

**Comment by wojtekmaj** [comment] 2018-11-02 11:04
@williamfsilva See #179
