### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by thebkht** [wojtekmaj/react-pdf#1858] opened 2024-08-20 06:10 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

![image](https://github.com/user-attachments/assets/3e149bb0-0bc0-4b54-a9a9-9a6ec6451c39)

### Steps to reproduce

run build command

### Expected behavior

must be build without error

### Actual behavior

..TypeError: Promise.withResolvers is not a function
    at file:///C:/Users/byusu/react-pdf/sample/next-pages/node_modules/pdfjs-dist/build/pdf.mjs:5448:35
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)

> Build error occurred
Error: Failed to collect page data for /Sample
    at C:\Users\byusu\react-pdf\sample\next-pages\node_modules\next\dist\build\utils.js:1268:15 {
  type: 'Error'
}

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: ^9.1.0
- **React version**: ^18.2.0
- **Bundler name and version (if applicable)**:

**Comment by wojtekmaj** [comment] 2024-08-22 16:35
Duplicate of #1811

**Closed by wojtekmaj** 2024-08-22 16:35 UTC
Labels: bug
