### ISSUE TITLE
How to cancel rendering pdf when open another page

### ISSUE THREAD

**Issue by nguyenhuutinh** [wojtekmaj/react-pdf#426] opened 2019-07-21 07:40 UTC
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

in PageInternal (created by Context.Consumer)
    in ForwardRef(Page)
    in div (created by Document)
    in Document
    in div (created by WingBlank)

**Comment by wojtekmaj** [comment] 2019-07-27 20:55
Duplicate of #353

**Closed by wojtekmaj** 2019-07-27 20:55 UTC
Labels: bug, duplicate
