### ISSUE TITLE
404 get request for pdf.worker.entry.js

### ISSUE THREAD

**Issue by ljsikuade** [wojtekmaj/react-pdf#315] opened 2018-12-06 12:49 UTC
The full error message: 
`pdf.worker.entry.js:2 GET http://localhost:8080/<hash>.worker.js 404 (Not Found)`
The code being referenced: 
`module.exports = function() {
  return new Worker(__webpack_public_path__ + "<hash>.worker.js");
};`

Currently I attempt to render the following jsx: 
`{this.state.openDocument && <Document file={myDocument} />}`
And I get an unending 'Loading PDF...' message. 

I'm importing react-pdf as: 
`import { Document } from "react-pdf/dist/entry.webpack";`
Which I've confirmed exists.

And my webpack looks as following: 

```
    const path = require("path");

    module.exports = {
      entry: "./src/index.js",
      devtool: "source-map",
      output: {
        filename: "bundle.js",
        path: path.resolve(__dirname, "static")
      },
      module: {
        rules: [
          {
            test: /\.js$/,
            exclude: /(node_modules)/,
            loader: require.resolve("babel-loader")
          },
          {
        
            test: /\.(pdf|gif|png|jpeg|svg)$/,
            use: [
              {
                loader: "file-loader",
                options: { outputPath: "dist" }
              },
              {
                loader: "image-webpack-loader"
              }
            ]
          },
         {
            test: /\.scss$/,
            use: [
              {
                loader: "style-loader"
              },
              {
                loader: "css-loader"
              },
              {
                loader: "sass-loader"
          }
        ]
      }
    ]
  }
};
```

A hashed .pdf appears in my 'static/dist' path on build. And in the 'static' path a hashed .worker.js file is also generated, along with a workerbundle. Which tells me that something is going right.

I tried one of the setOptions approaches last night, but can only remember that it produced build errors for me. 

**Environment**
-React PDF version: 4.0.0
-Webpack version: 4.12.0
-react: ^16.2.0
-Chrome 70

**Comment by wojtekmaj** [comment] 2018-12-09 11:10
Duplicate of #164, missing publicPath I suppose.

**Closed by wojtekmaj** 2018-12-09 11:10 UTC

**Comment by wojtekmaj** [comment] 2018-12-09 11:16
Duplicate of #97 too
