### ISSUE TITLE
digest digest: "256245278"

### ISSUE THREAD

**Issue by ltsmeShubham12** [wojtekmaj/react-pdf#1866] opened 2024-08-31 06:58 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

While my pdf is in the production it is throwing me this error in the server again and again

 ⨯ TypeError: Promise.withResolvers is not a function
    at __webpack_require__ (C:\Users\Amogh\Desktop\Amogh-website\com.newamoghbuildtech.web\.next\server\webpack-runtime.js:33:43)
    at eval (./src/app/projects/[propertyId]/page.tsx:51:68)
    at (ssr)/./src/app/projects/[propertyId]/page.tsx (C:\Users\Amogh\Desktop\Amogh-website\com.newamoghbuildtech.web\.next\server\app\projects\[propertyId]\page.js:467:1)       
    at Object.__webpack_require__ [as require] (C:\Users\Amogh\Desktop\Amogh-website\com.newamoghbuildtech.web\.next\server\webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
digest: "256245278"

### Steps to reproduce

import { pdfjs } from "react-pdf";
import { GrMapLocation } from "react-icons/gr";
import { Spin } from "antd";
import { log } from "console";

const Document = dynamic(
  () => import("react-pdf").then((mod) => mod.Document),
  { ssr: false } // Disable SSR
);

const Page = dynamic(
  () => import("react-pdf").then((mod) => mod.Page),
  { ssr: false } // Disable SSR
);

### Expected behavior

const [numPages, setNumPages] = useState<number>(0);
  const [pageNumber, setPageNumber] = useState<number>(1);
  const [containerWidth, setContainerWidth] = useState<number>(0);
  const [scale, setScale] = useState<number>(1.0);
  const [isFullScreen, setIsFullScreen] = useState<boolean>(false);
  const [flipDirection, setFlipDirection] = useState<"left" | "right" | null>(
    null
  );
  const containerRef = useRef<HTMLDivElement>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const [isAudioLoaded, setIsAudioLoaded] = useState<boolean>(false);

  useEffect(() => {
    const audio = new Audio("/pageturn.mp3");
    audio.addEventListener("canplaythrough", () => {
      setIsAudioLoaded(true);
    });
    audioRef.current = audio;

    return () => {
      audio.removeEventListener("canplaythrough", () => {
        setIsAudioLoaded(true);
      });
    };
  }, []);

  useEffect(() => {
    const updateWidth = () => {
      if (containerRef.current) {
        setContainerWidth(containerRef.current.offsetWidth - 2);
      }
    };

    updateWidth();
    window.addEventListener("resize", updateWidth);

    return () => {
      window.removeEventListener("resize", updateWidth);
    };
  }, []);

  const onDocumentLoadSuccess = ({ numPages }: { numPages: number }) => {
    setNumPages(numPages);
  };

  const playPageFlipSound = () => {
    if (isAudioLoaded && audioRef.current) {
      audioRef.current.currentTime = 0;
      audioRef.current
        .play()
        .catch((error) => console.error("Error playing audio:", error));
    }
  };

  const changePage = (newPageNumber: number) => {
    if (
      newPageNumber !== pageNumber &&
      newPageNumber >= 1 &&
      newPageNumber <= numPages
    ) {
      const direction = newPageNumber > pageNumber ? "right" : "left";
      setFlipDirection(direction);
      playPageFlipSound();
      setTimeout(() => {
        setPageNumber(newPageNumber);
      }, 300);
      setTimeout(() => {
        setFlipDirection(null);
      }, 500);
    }
  };

  const goToPreviousPage = () => {
    changePage(pageNumber - 1);
  };

  const goToNextPage = () => {
    changePage(pageNumber + 1);
  };

  const handleZoom = (event: React.WheelEvent<HTMLDivElement>) => {
    const delta = event.deltaY;
    if (delta < 0) {
      setScale((prevScale) => Math.min(prevScale + 0.1, 2.0));
    } else {
      setScale((prevScale) => Math.max(prevScale - 0.1, 0.5));
    }
  };

  const zoomIn = () => {
    setScale((prevScale) => Math.min(prevScale + 0.2, 2.0));
  };

  const zoomOut = () => {
    setScale((prevScale) => Math.max(prevScale - 0.2, 0.5));
  };

  const toggleFullScreen = () => {
    if (containerRef.current) {
      if (!document.fullscreenElement) {
        containerRef.current.requestFullscreen();
      } else {
        document.exitFullscreen();
      }
      setIsFullScreen(!document.fullscreenElement);
    }
  };

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "ArrowLeft") {
        goToPreviousPage();
      } else if (event.key === "ArrowRight") {
        goToNextPage();
      }
    };

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [pageNumber, numPages]);

  const handleLoadError = (error: Error) => {
    console.error("Failed to load PDF:", error.message);
  };

  pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.mjs`;

  const ThumbnailIcon: React.FC<ThumbnailIconProps> = ({
    numPages,
    pdfPath,
    setPageNumber,
  }) => {
    const [showThumbnails, setShowThumbnails] = useState<boolean>(false);

    return (
      <div className="">
        <FileImageOutlined
          className="text-2xl cursor-pointer"
          onClick={() => setShowThumbnails(true)}
        />
        {showThumbnails && (
          <div className="thumbnail-box  mb-4 border-red-400 border-[4px]">
            <div className=" flex justify-between border-b w-full items-center p-2 sticky top-[-2px] bg-white z-10">
              <p className="text-xs relative right-6 font-bold">Thumbnails</p>
              <ImCross
                className="text-sm cursor-pointer"
                onClick={() => setShowThumbnails(false)}
              />
            </div>
            <div className="thumbnail-grid border grid grid-cols-2 gap-2 p-2 max-h-60 overflow-y-auto">
              {Array.from(new Array(numPages), (_, index) => (
                <div
                  key={`thumb_${index + 1}`}
                  className="thumbnail-item border border-gray-300"
                  onClick={() => {
                    setPageNumber(index + 1);
                    setShowThumbnails(false);
                  }}
                >
                  <Document file={pdfPath}>
                    <Page
                      pageNumber={index + 1}
                      width={80}
                      renderMode="canvas"
                      renderTextLayer={false}
                      renderAnnotationLayer={false}
                    />
                  </Document>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  };

### Actual behavior

const [numPages, setNumPages] = useState<number>(0);
  const [pageNumber, setPageNumber] = useState<number>(1);
  const [containerWidth, setContainerWidth] = useState<number>(0);
  const [scale, setScale] = useState<number>(1.0);
  const [isFullScreen, setIsFullScreen] = useState<boolean>(false);
  const [flipDirection, setFlipDirection] = useState<"left" | "right" | null>(
    null
  );
  const containerRef = useRef<HTMLDivElement>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const [isAudioLoaded, setIsAudioLoaded] = useState<boolean>(false);

  useEffect(() => {
    const audio = new Audio("/pageturn.mp3");
    audio.addEventListener("canplaythrough", () => {
      setIsAudioLoaded(true);
    });
    audioRef.current = audio;

    return () => {
      audio.removeEventListener("canplaythrough", () => {
        setIsAudioLoaded(true);
      });
    };
  }, []);

  useEffect(() => {
    const updateWidth = () => {
      if (containerRef.current) {
        setContainerWidth(containerRef.current.offsetWidth - 2);
      }
    };

    updateWidth();
    window.addEventListener("resize", updateWidth);

    return () => {
      window.removeEventListener("resize", updateWidth);
    };
  }, []);

  const onDocumentLoadSuccess = ({ numPages }: { numPages: number }) => {
    setNumPages(numPages);
  };

  const playPageFlipSound = () => {
    if (isAudioLoaded && audioRef.current) {
      audioRef.current.currentTime = 0;
      audioRef.current
        .play()
        .catch((error) => console.error("Error playing audio:", error));
    }
  };

  const changePage = (newPageNumber: number) => {
    if (
      newPageNumber !== pageNumber &&
      newPageNumber >= 1 &&
      newPageNumber <= numPages
    ) {
      const direction = newPageNumber > pageNumber ? "right" : "left";
      setFlipDirection(direction);
      playPageFlipSound();
      setTimeout(() => {
        setPageNumber(newPageNumber);
      }, 300);
      setTimeout(() => {
        setFlipDirection(null);
      }, 500);
    }
  };

  const goToPreviousPage = () => {
    changePage(pageNumber - 1);
  };

  const goToNextPage = () => {
    changePage(pageNumber + 1);
  };

  const handleZoom = (event: React.WheelEvent<HTMLDivElement>) => {
    const delta = event.deltaY;
    if (delta < 0) {
      setScale((prevScale) => Math.min(prevScale + 0.1, 2.0));
    } else {
      setScale((prevScale) => Math.max(prevScale - 0.1, 0.5));
    }
  };

  const zoomIn = () => {
    setScale((prevScale) => Math.min(prevScale + 0.2, 2.0));
  };

  const zoomOut = () => {
    setScale((prevScale) => Math.max(prevScale - 0.2, 0.5));
  };

  const toggleFullScreen = () => {
    if (containerRef.current) {
      if (!document.fullscreenElement) {
        containerRef.current.requestFullscreen();
      } else {
        document.exitFullscreen();
      }
      setIsFullScreen(!document.fullscreenElement);
    }
  };

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "ArrowLeft") {
        goToPreviousPage();
      } else if (event.key === "ArrowRight") {
        goToNextPage();
      }
    };

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [pageNumber, numPages]);

  const handleLoadError = (error: Error) => {
    console.error("Failed to load PDF:", error.message);
  };

  pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.mjs`;

  const ThumbnailIcon: React.FC<ThumbnailIconProps> = ({
    numPages,
    pdfPath,
    setPageNumber,
  }) => {
    const [showThumbnails, setShowThumbnails] = useState<boolean>(false);

    return (
      <div className="">
        <FileImageOutlined
          className="text-2xl cursor-pointer"
          onClick={() => setShowThumbnails(true)}
        />
        {showThumbnails && (
          <div className="thumbnail-box  mb-4 border-red-400 border-[4px]">
            <div className=" flex justify-between border-b w-full items-center p-2 sticky top-[-2px] bg-white z-10">
              <p className="text-xs relative right-6 font-bold">Thumbnails</p>
              <ImCross
                className="text-sm cursor-pointer"
                onClick={() => setShowThumbnails(false)}
              />
            </div>
            <div className="thumbnail-grid border grid grid-cols-2 gap-2 p-2 max-h-60 overflow-y-auto">
              {Array.from(new Array(numPages), (_, index) => (
                <div
                  key={`thumb_${index + 1}`}
                  className="thumbnail-item border border-gray-300"
                  onClick={() => {
                    setPageNumber(index + 1);
                    setShowThumbnails(false);
                  }}
                >
                  <Document file={pdfPath}>
                    <Page
                      pageNumber={index + 1}
                      width={80}
                      renderMode="canvas"
                      renderTextLayer={false}
                      renderAnnotationLayer={false}
                    />
                  </Document>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  };

### Additional information

<div className="mt-4 border p-2 md:mb-8">
                  <p className="text-lg font-semibold mb-4">{data?.name}</p>
                  <div
                    ref={containerRef}
                    className={`pdf-container`}
                    style={{
                      height: "300px",
                      border: "1px solid #ddd",
                      overflow: "hidden",
                      position: "relative",
                      display: "flex",
                      justifyContent: "center",
                      alignItems: "center",
                    }}
                    onWheel={handleZoom}
                  >
                    <Document
                      file={`/api/pdf/${data?.pdf}`}
                      onLoadSuccess={onDocumentLoadSuccess}
                      onLoadError={handleLoadError}
                    >
                      <div
                        className={`page-wrapper ${
                          flipDirection ? `flipping-${flipDirection}` : ""
                        }`}
                      >
                        {pageNumber > 1 && (
                          <Page
                            key={`page_${pageNumber - 1}`}
                            pageNumber={pageNumber - 1}
                            width={(containerWidth / 2) * scale}
                            height={250 * scale}
                            renderMode="canvas"
                            className="page-left"
                            renderTextLayer={false}
                            renderAnnotationLayer={false}
                          />
                        )}
                        <Page
                          key={`page_${pageNumber}`}
                          pageNumber={pageNumber}
                          width={(containerWidth / 2) * scale}
                          height={250 * scale}
                          renderMode="canvas"
                          className="page-right"
                          renderTextLayer={false}
                          renderAnnotationLayer={false}
                        />
                      </div>
                    </Document>
                    <div
                      className="navigation-buttons bg-white p-1 rounded-full"
                      style={{
                        left: "20px",
                        position: "absolute",
                        top: "50%",
                        transform: "translateY(-50%)",
                      }}
                    >
                      <LeftOutlined onClick={goToPreviousPage} />
                    </div>
                    <div
                      className="navigation-buttons bg-white p-1 rounded-full"
                      style={{
                        right: "20px",
                        position: "absolute",
                        top: "50%",
                        transform: "translateY(-50%)",
                      }}
                    >
                      <RightOutlined onClick={goToNextPage} />
                    </div>
                  </div>
                  <div className="controls flex flex-wrap md:flex-nowrap items-center md:justify-between mt-2 relative">
                    <div className="flex ml-4 flex-wrap md:flex-nowrap items-center space-x-2 md:space-x-4 w-full md:w-auto">
                      <ThumbnailIcon
                        numPages={numPages}
                        pdfPath={`/pdfs/${data?.pdf}`}
                        setPageNumber={changePage}
                      />
                      <div className="zoom-buttons flex space-x-2">
                        <ZoomInOutlined onClick={zoomIn} />
                        <ZoomOutOutlined onClick={zoomOut} />
                      </div>
                      <PiArrowSquareLeftFill
                        onClick={goToPreviousPage}
                        size={24}
                      />
                      <p className="rounded flex items-center space-x-1">
                        <span className="bg-gray-200 px-2 py-[1px]">
                          {pageNumber}
                        </span>
                        <span className="bg-gray-400 px-2 py-[1px]">
                          {numPages}
                        </span>
                      </p>
                      <PiArrowSquareRightFill
                        onClick={goToNextPage}
                        size={24}
                      />
                      <PrinterOutlined
                        onClick={() => showModal(data)}
                        className="ml-1"
                      />
                      <FullscreenOutlined
                        onClick={toggleFullScreen}
                        size={24}
                      />
                      <button
                        onClick={() => showModal(data)}
                        type="submit"
                        className="border md:absolute right-0 border-[#FF5C29] md:ml-2 px-2 py-2 bg-[#FF5C29] rounded text-xs text-white hover:bg-[#FF5C29] transition-all duration-300 cursor-pointer mt-2 md:mt-0"
                      >
                        <FaRegFilePdf className="inline-block text-base animate-blink" />
                        Download
                      </button>
                    </div>
                  </div>
                </div>

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Bundler name and version (if applicable)**:

**Comment by wojtekmaj** [comment] 2024-09-01 14:16
Duplicate of #1811

**Closed by wojtekmaj** 2024-09-01 14:16 UTC
Labels: bug
