### ISSUE TITLE
Critical dependency warnings

### ISSUE THREAD

**Issue by cipacda** [wojtekmaj/react-pdf#471] opened 2019-10-23 07:39 UTC
**Before you start - checklist**

 - [ x ] I followed instructions in documentation written for my React-PDF version
 - [ x ] I have checked if this bug is not already reported
 - [ x ] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

Using Create React App with typescript and React 16.8.6, I get the following warning: `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

**Steps to reproduce**

Simply use it within a similar environment.

**Expected behavior**

What you expected to happen?

The warning should not be there.

**Environment**

 - Browser (if applicable): Chrome
 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.8.6
 - Webpack version (if applicable) [e.g. 4.16.2]: react-scripts 3.0.0

**Comment by wojtekmaj** [comment] 2019-11-14 13:45
Duplicate of #280

**Closed by wojtekmaj** 2019-11-14 13:45 UTC
