### ISSUE TITLE
4.0.2 file param object with `withCredentials` causes onLoadSuccess fired infinitely

### ISSUE THREAD

**Issue by chinalwb** [wojtekmaj/react-pdf#331] opened 2019-01-10 02:53 UTC
React : 16.6.3
webpack: 4.27
browser: Chrome

With 4.0.2, the following code fires the 'onLoadSuccess' infinitely.

```
<Document
          file={{
             url: 'https://www.tutorialspoint.com/android/android_tutorial.pdf',
             withCredentials: true, // This causes the issue, without this, it will be OK
          }}
          onLoadSuccess={this.onDocumentLoadSuccess}
        >
          <Page pageNumber={pageNumber}  />
        </Document>
```

**Comment by chinalwb** [comment] 2019-01-10 03:01
Actually the issue starts from '4.0.0-beta'. 3.0.6 works well to me.

**Comment by wojtekmaj** [comment] 2019-01-10 10:21
Duplicate of #308

**Comment by wojtekmaj** [comment] 2019-01-10 10:21
Technically it's not a bug, you provide a new config with each render. Although this situation is too common to be ignored, so you'll find the solution in #308, too, until this gets fixed.

**Closed by wojtekmaj** 2019-01-10 10:21 UTC

**Comment by chinalwb** [comment] 2019-01-10 13:21
Thanks! I followed your directions in 308, it works now!

Thanks for the support and this great library!
