### ISSUE TITLE
Setting up fake worker failed: "Cannot read properties of undefined (reading 'WorkerMessageHandler')"

### ISSUE THREAD

**Issue by Mani-RDev** [wojtekmaj/react-pdf#1697] opened 2024-01-17 13:23 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

 const MyPdfViewer = (base64) => {
        return (
            <Document file={`data:application/pdf;base64,${base64)`}
                 <Page pageNumber={1} />
            </Document>
            );
       };

### Steps to reproduce

 const MyPdfViewer = (base64) => {
        return (
            <Document file={`data:application/pdf;base64,${base64)`}
                 <Page pageNumber={1} />
            </Document>
            );
       };
I tried to render Pdf But  i Can't Below error are getting in console 

### Expected behavior

PDF Should View In a Another component That i use MyPdfViewer  this method.

### Actual behavior

![image](https://github.com/wojtekmaj/react-pdf/assets/76480543/d1bd638e-6ff7-42e1-933b-d35d28194534)
![Screenshot 2024-01-17 185030](https://github.com/wojtekmaj/react-pdf/assets/76480543/a3e9eb0a-e654-4348-945d-511d0f0d6fb7)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by ManigandanMani** [comment] 2024-01-17 13:38
i'm trying to render here
const rootElement = document.getElementById("root");
ReactDOM.render(<MyPdfViewer />, rootElement);

**Comment by aleksbobic** [comment] 2024-02-13 07:35
Hi @wojtekmaj I'm encountering the same issue. My Webpack config is the default [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate). It works perfectly fine when loaded via CDN so I assume it's a Webpack issue.

**Comment by wojtekmaj** [comment] 2024-02-13 10:48
Duplicate of #677

**Closed by wojtekmaj** 2024-02-13 10:48 UTC
Labels: bug
