### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory with CRA 5, react-pdf v 5.6.0

### ISSUE THREAD

**Issue by toni123321** [wojtekmaj/react-pdf#937] opened 2022-01-26 15:08 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I have tried the solutions in other issues on this topic but nothing works for me.
I am using a react app created with CRA 5. 

What I have tried?
1) I have tried to use this two ways of importing Document and Page:
- import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
- import { Document, Page } from 'react-pdf';

2) I have tried this as well:
- Standard instructions will also work with Create React App. Please note that in CRA, you can copy pdf.worker.js file from pdfjs-dist/legacy/build to public directory in order for it to be copied to your project's output folder at build time.

3) Edit react scripts in package json:
`"scripts": {
    "start": "react-scripts --max_old_space_size=8192  start",
    "build": "react-scripts --max_old_space_size=8192  build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },`

Nothing works for me.
So could you help me fix the issue, please?

PdfViewer.js
`import React, { useState } from 'react';
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import myCV from "../resources/files/Antonio_Takev-CV.pdf";

function PdfViewer(props) {
    const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return (
    <div>
      <Document
        file={myCV}
        onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page pageNumber={pageNumber} />
      </Document>
      <p>Page {pageNumber} of {numPages}</p>
    </div>
  );
}

export default PdfViewer;`

package.json scripts
`"scripts": {
    "start": "react-scripts  start",
    "build": "react-scripts  build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },`

package.json versions
`    "react-dom": "^17.0.2",
    "react-pdf": "^5.6.0",
    "react-router-dom": "^6.2.1",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.2"
  },`

### Steps to reproduce

1)Create react app with:
- CRA 5 (react script version 5.0.0
2) Install dependency react-pdf - version 5.6.0
3) Create PdfViewer.js file where to put the pdf loading logic and put it in App.js (in my case I placed it Home.js component)
4) run with npm start the project

### Expected behavior

Once I run npm start I got the error placed below after some time
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### Actual behavior

npm start to start the server normally and PdfViewer to load my pdf file on Home page of my website.

### Environment

- **Browser (if applicable)**: Google Chrome
- **React-PDF version**: 5.6.0
- **React version**: 17.0.2
- React scripts: 5.0.0

**Comment by kristianstroka** [comment] 2022-01-26 22:09
I have same on my side ... is there any solution for that? :)

**Comment by wojtekmaj** [comment] 2022-01-27 10:47
Duplicate of #912

See also https://github.com/wojtekmaj/react-pdf/issues/912#issuecomment-1016836101, [v5.7.0 release](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.7.0) which ships numerous improvements including some for Webpack 5 and CRA 5, and last but not least, [updated README](https://github.com/wojtekmaj/react-pdf#create-react-app).

**Closed by wojtekmaj** 2022-01-27 10:47 UTC
Labels: bug

**Comment by toni123321** [comment] 2022-01-27 12:07
Thank you, but I can't make it work still. I clone your repo and try your example but it doesn't work for me. 
Give me this error:
Failed to load config "wojtekmaj/react" to extend from.

So could you help me?

**Comment by toni123321** [comment] 2022-01-27 12:08
Thank you, but I can't make it work still. I clone your repo and try your example but it doesn't work for me. 
Give me this error:
Failed to load config "wojtekmaj/react" to extend from.

So could you help me?

**Comment by toni123321** [comment] 2022-01-27 13:26
UPDATE!!!
I made it working. I used this imports in my PdfViewer.js file: 

```
import { pdfjs, Document, Page } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
```

**Comment by fwx5618177** [comment] 2022-02-04 18:38
Upgrade to `react-pdf@5.7.0` would fix this bug.

**Comment by nabeelpkl** [comment] 2023-01-27 03:44
still facing this issue on react-pdf 6.2.2

**Comment by wojtekmaj** [comment] 2023-02-10 10:56
@nabeelpkl You might want to host the worker file yourself, depending on your specific requirements and policies, but it's a one of a few perfectly valid ways to run React-PDF :)
