### ISSUE TITLE
require is not defined -  pdf is not rendered on Chrome 

### ISSUE THREAD

**Issue by tomaszzmudzinski** [wojtekmaj/react-pdf#782] opened 2021-05-12 09:28 UTC
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

After updating the react-pdf library from 5.2.0 to 5.3.0 pdf stopped being rendered on Chrome. All I can see is: Failed to load PDF file.

On the google chrome console I can find:

Uncaught ReferenceError: require is not defined

<img width="1680" alt="Zrzut ekranu 2021-05-12 o 11 21 46" src="https://user-images.githubusercontent.com/4519335/117951294-54e5db80-b314-11eb-91e7-6b1b7bb30626.png">

<img width="1070" alt="Zrzut ekranu 2021-05-12 o 11 22 07" src="https://user-images.githubusercontent.com/4519335/117951308-57e0cc00-b314-11eb-9fc7-389080e5f79c.png">

This problem exists only on google chrome because everything works without any problem on Firefox 88.0.

**Environment**
 - Browser: Chrome 90
 - React-PDF version: 5.3.0
 - React version: 17.0.2
 - Webpack version: 4.44.2

**Comment by jorge-uproar** [comment] 2021-05-13 18:43
I have the same issue but my react-pdf version is 5.2.0 I just remember updating npm to the lts

**Comment by abdulrehman1937** [comment] 2021-05-16 10:44
Same issue working fine in dev but gives error in production. Tested on chrome and edge.

**Comment by tomaszzmudzinski** [comment] 2021-05-16 18:14
> Same issue working fine in dev but gives error in production. Tested on chrome and edge.

Exactly! It works in the local environment and the problem exists on production with chrome/edge browsers

**Comment by Denpex** [comment] 2021-05-17 14:13
Can confirm we are experiencing the same issue on production ( development works fine ). Currently using yarn 1.22.4 with node 14.5.1 with create react app.

**Comment by jorge-uproar** [comment] 2021-05-17 14:21
I managed to solve this problem in the following way:

1. Instead of use 'react-pdf/dist/esm/entry.parcel' or 'react-pdf/dist/umd/entry.parcel' just use only the direct 'react-pdf'
2. Since you are going to use this direct reference so you need to copy 'pdfjs-dist/build/pdf.worker.js' to your public folder
3. Then you'll have to import it in this way: pdfjs.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.js';

<img width="714" alt="Screen Shot 2021-05-17 at 9 17 50 AM" src="https://user-images.githubusercontent.com/65964744/118504008-c21cb680-b6f0-11eb-8660-6c4814144cdf.png">

I used to use the Document from 'react-pdf/dist/esm/entry.parcel' but since I started having the required error I had to switch to that other way

**Comment by andreareginato** [comment] 2021-05-20 11:12
> I managed to solve this problem in the following way:
> 
> 1. Instead of use 'react-pdf/dist/esm/entry.parcel' or 'react-pdf/dist/umd/entry.parcel' just use only the direct 'react-pdf'
> 2. Since you are going to use this direct reference so you need to copy 'pdfjs-dist/build/pdf.worker.js' to your public folder
> 3. Then you'll have to import it in this way: pdfjs.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.js';

I've been following the suggested steps but i still get the error `Uncaught ReferenceError: require is not defined` in production (in development it works correctly). Before the error I also see in console `Warning: Setting up fake worker.`

```
import { Document, Page, pdfjs } from 'react-pdf';
/** /pdf.worker.min.js accessible form public at /pdf.worker.min.js */
pdfjs.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.js';
```

Any other suggestion to overcome the current issue?

**Comment by Denpex** [comment] 2021-05-20 15:05
Hi @andreareginato, the only way I know that is going to work is by going to your `package.json` file and setting the version of react-pdf to 5.2.0 ( directly copied from my package.json file `"react-pdf": "5.2.0" ). After explicitly setting the version do a `npm i` or `yarn install` so that the new changes take effect. 

Side note: 
Make sure to remove the symbol `^` before the version number of the package as this will cause the package manager npm or yarn to always install the latest version of the package which is the 5.3.0 that has this bug. 

Will work ✅: 
`"react-pdf": "5.2.0" `

Won't work 🛑: 
`"react-pdf": "^5.2.0" `

**Comment by slugmandrew** [comment] 2021-05-21 09:12
@Denpex Thanks so much!

**Comment by andreareginato** [comment] 2021-05-25 10:47
@Denpex thanks, it worked.

**Comment by starloveit** [comment] 2021-06-02 17:48
@Denpex thank you, it is working

**Comment by sm3sher** [comment] 2021-07-09 06:50
As of for now `"react-pdf": "5.3.2"` still has the same issue. Is there any progress on this, I don't want to miss out on newer versions of this great library.

**Comment by tomaszzmudzinski** [comment] 2021-07-14 10:16
@wojtekmaj any progress on this? :)

**Comment by wojtekmaj** [comment] 2021-07-14 19:35
Nope, still no idea what the fix could look like. I'm also not getting it in any of my personal projects. These are based on Webpack 5 though so maybe the issue is affecting Webpack 4 only?

**Comment by uwemneku** [comment] 2021-07-20 21:11
> Hi @andreareginato, the only way I know that is going to work is by going to your `package.json` file and setting the version of react-pdf to 5.2.0 ( directly copied from my package.json file `"react-pdf": "5.2.0"` ). After explicitly setting the version do a `npm i` or `yarn install` so that the new changes take effect.
> 
> Side note:
> Make sure to remove the symbol `^` before the version number of the package as this will cause the package manager npm or yarn to always install the latest version of the package which is the 5.3.0 that has this bug.
> 
> Will work ✅:
> `"react-pdf": "5.2.0" `
> 
> Won't work 🛑:
> `"react-pdf": "^5.2.0" `

This solution worked for me

**Comment by LiHaoGit** [comment] 2021-07-23 07:39
```js
import { Document, Page, pdfjs } from 'react-pdf/dist/esm/entry.webpack'

const url = `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`
pdfjs.GlobalWorkerOptions.workerSrc = url
```
work for me

**Comment by PCOffline** [comment] 2021-08-11 14:06
What makes it run locally but not on the dev/prod environment though?

**Comment by wojtekmaj** [comment] 2021-08-13 09:42
I've set up sample repos on my server here:

https://projects.wojtekmaj.pl/react-pdf/webpack4/
https://projects.wojtekmaj.pl/react-pdf/webpack5/

URLs are self-explanatory I think. Looks like both built and dev code works for me with default entry. I'm using the latest React-PDF version here. Anyone can reproduce this issue on the pages above?

**Comment by PCOffline** [comment] 2021-08-16 07:06
Can you provide the source code in jsfiddle?

**Comment by komret** [comment] 2021-08-17 08:10
I have the same problem using `react-pdf 5.3.2`, `react 17.0.2` and `create-react-app 4.0.3` (i.e. `webapack 4`). When I import `Document` and `Page`  from `react-pdf/dist/esm/entry.webpack` (or `react-pdf/dist/umd/entry.webpack`) and build the project, it outputs an extra file (plus a license file) into the build directory which causes the error. It does not appear in development because the build files are not used when running from webpack devServer. I had the error not only in Chrome but also Firefox.

The solution suggested by @jorge-uproar or import from CDN works for me.

**Comment by PandaPandaPanda** [comment] 2021-09-15 06:07
This bug costed me half a day. Thank you for saving me out of my misery.  
Denpex's solution works

**Comment by peterpeterparker** [comment] 2021-09-30 13:35
[v5.4.0](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.4.0) that has been released 3 days ago seems to have solve the issue for me.

Today I have also upgraded to Node v16 and npm v7, but do think the above release fixed it. In any case, build the app and deployed it on staging and did not had the error anymore.

Note: I use the `esm` version

```
import {Document, Page} from 'react-pdf/dist/esm/entry.webpack';
```

**Comment by sm3sher** [comment] 2021-09-30 13:53
> As of for now `"react-pdf": "5.3.2"` still has the same issue. Is there any progress on this, I don't want to miss out on newer versions of this great library.

This seems to be indeed fixed in [v5.4.0](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.4.0).
@tomaszzmudzinski can you confirm and close this issue?

**Comment by Tjeerd** [comment] 2021-11-01 20:37
New release fixed it for me as well!

**Comment by wojtekmaj** [comment] 2021-11-02 10:27
Great - I'm closing this ticket then until anyone else complains about the exact same thing in the new versions.

**Closed by wojtekmaj** 2021-11-02 10:27 UTC
Labels: bug, help wanted

**Comment by Cayan** [comment] 2022-08-22 18:31
This issue is happening again on [v6.0.0-beta.3](https://github.com/wojtekmaj/react-pdf/releases/tag/v6.0.0-beta.3)

Downgrading to `5.7.2` fixed it.

Relates to #852

**Comment by wojtekmaj** [comment] 2022-11-22 19:14
Is there a reproducible example you can share @sm3sher?

**Comment by mikegoatly** [comment] 2022-12-06 09:46
@sm3sher Are you [copying pdf.worker.js](https://github.com/wojtekmaj/react-pdf#standard-browserify-esbuild-and-others) to your project's output folder? 

After I upgraded to v6 I noticed that I'd completely missed that step when I got started while using v5 and adding it via the CDN option got things working again.

**Comment by sm3sher** [comment] 2022-12-06 16:12
I tried the first option and unfortunately it was not working with this solution:

`
pdfjs.GlobalWorkerOptions.workerSrc = 'pdf.worker.min.js';
`

The CDN option worked out but I have react-apps that run inside a local context without internet access.

**Comment by entrust-ajit** [comment] 2022-12-16 19:23
> For now @LiHaoGit 's CDN solution worked for me, also with webpack5 import.

I am also using react-pdf version "^6.2.0" and running React "^18.1.0". I tried to implement @LiHaoGit 's CDN solution, but it didnt work for me. It is not throwing any error on the console as well. Below is my code. Any help is highly appreciated.

import React, { useState } from 'react';
import { Document, Page, pdfjs } from 'react-pdf/dist/esm/entry.webpack5';
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
import 'react-pdf/dist/esm/Page/TextLayer.css';
import './PdfViewerTemplate.less';
const url = `//cdn.jsdelivr.net/npm/pdfjs-dist@3.1.81/build/pdf.worker.min.js`
pdfjs.GlobalWorkerOptions.workerSrc = url

const options = {
  cMapUrl: 'cmaps/',
  cMapPacked: true,
  standardFontDataUrl: 'standard_fonts/',
};

export const PdfViewerTemplate = ({props}) => {
    const [pdfFileData, setPdfFileData] = useState(_base64ToArrayBuffer(props));
    const [numPages, setNumPages] = useState(null);
    const [pageNumber, setPageNumber] = useState(1);
    const [renderNavButtons, setRenderNavButtons] = useState(false);

    function _base64ToArrayBuffer(base64) {
      var binary_string = window.atob(base64);
      var len = binary_string.length;
      var bytes = new Uint8Array(len);
      for (var i = 0; i < len; i++) {
          bytes[i] = binary_string.charCodeAt(i);
      }
      return bytes.buffer;
    }

    const onSuccess = () => {
      setPageNumber(1);
      setRenderNavButtons(true);
    }
  
    const changePage = (offset) => {
      setPageNumber(prevPageNumber => prevPageNumber + offset);
    }

    const previousPage = () => { changePage(-1); }
    
    const nextPage = () => { changePage(+1); }

    return (
      <div className="Pdfview">
        <div className="Pdfview__container">
        <div className="Pdfview__container__document">
        <Document file={{data: pdfFileData}} 
                  onLoadSuccess={({ numPages }) => {
                    setNumPages(numPages);
                    setRenderNavButtons(true);
                    onSuccess;
                  }} 
                  options={options}>
        <Page pageNumber={pageNumber} width={400} height={500} scale={1.0}/>
        {renderNavButtons &&
        <div>
          <button
            className={pageNumber <= 1 ? 'disabled-form-button' : 'form-button'}
            onClick={previousPage}
          >
            Previous
          </button>
          <button
            className={pageNumber === numPages ? 'disabled-form-button' : 'form-button'}
            onClick={nextPage}
          >
            Next
          </button>
        </div>}
        </Document>
        </div>
        </div>
      </div>
  );
}

**Comment by rashadatjou** [comment] 2023-01-10 08:43
Does this issue need help fixing? I would like to give it a try? @andreareginato @wojtekmaj

**Comment by wojtekmaj** [comment] 2023-01-11 08:10
@rashadatjou Yes, if it's still reproducible then yes. We have a bunch of sample repositories in here to test React-PDF with CRA5, Webpack 4, Webpack 5 and others, but it seems it's not enough.

**Comment by nocive** [comment] 2023-01-16 12:07
should this ticket be reopened then?

**Comment by carlossalasamper** [comment] 2023-01-24 14:20
`import { Document, Page } from "react-pdf/dist/esm/entry.webpack5";
`
In version 6.2.2 getting the same error

**Comment by zwarrell** [comment] 2023-01-29 04:10
I am running react-pdf 6.2.2 and had this error.  I got everything working with.
`import { Document, Page, pdfjs } from 'react-pdf';`
`pdfjs.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.2.16.105.js'`

I downloaded the pdf.worker.min.js from this link (https://cdn.jsdelivr.net/npm/pdfjs-dist@2.16.105/build/pdf.worker.min.js) and put it in my public directory named as (pdf.worker.min.2.16.105.js) so I am not dependent on a CDN.

Hope this helps someone else! 

This library is awesome!

**Comment by abacaj** [comment] 2023-02-03 01:42
Was trying to fix this issue, then decided I should see if someone else had it.

Turns out from all of the folks here having the same issue - it's extremely hard to get a pdf document loaded on the browser using create-react-app.

Only solution that worked me is:

```
import { Document, Page, pdfjs } from 'react-pdf/dist/esm/entry.webpack';
const url = `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;
pdfjs.GlobalWorkerOptions.workerSrc = url;
```

On react 17, react-scripts 4.0.3

**Comment by dbouclier** [comment] 2023-02-10 09:18
Same issue for me,

work around work with both  `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/{pdfjs.version}/pdf.worker.min.js `
or  `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;

but we expect the library should come with all the dependencies, @wojtekmaj so I guess this issue is still  open, no?

**Comment by wojtekmaj** [comment] 2023-02-10 10:47
@dbouclier You're correct, but this issue is not reproducible in any of our existing samples, so I'll need one to look into this matter closely.

**Comment by dbouclier** [comment] 2023-02-10 21:10
@wojtekmaj  I got this issue only with production build, everything was working locally.

no sure the samples are using the same dependencies as me
(basically yarn + typescript + CRA5 + react 18 + webpack5)

 details : 
   ```
    "dependencies": {
        "react": "^18.2.0",
        "react-pdf": "^6.2.2",
    },

    "devDependencies": {
        "@types/node": "^16.11.65",
        "@types/react": "^18.0.26",
        "@types/react-pdf": "^6.2.0",
        "react-scripts": "^5.0.1",
        "typescript": "^4.9.4",
        "webpack": "^5.75.0"
    },

    "packageManager": "yarn@3.2.3"

   ```


How I can help ?  do you need more details ?

**Comment by allicanseenow** [comment] 2023-02-20 13:28
Yeah. I've found out that this issue doesn't happen with the dev env. But if you build it and run the prod build on localhost, you can see the issue if you don't set ```pdfjs.GlobalWorkerOptions.workerSrc```

**Comment by jack-bgl** [comment] 2023-02-27 10:04
Seem issue with my project, "react-pdf": "^5.7.1"
Should open this again?

**Comment by rashadatjou** [comment] 2023-03-01 16:40
This bug only happens with create-react apps (I suspect it is something with how babel works with create-react-app). I was able to recreate the bug on the sample `create-react-app-5`. I have made a fork to fix to the sample `create-react-app-5` as It is broken currently and does not work: https://github.com/wojtekmaj/react-pdf/pull/1358.

@wojtekmaj You can go to my fork https://github.com/rashadatjou/react-pdf and when you build the `create-react-app-5` sample with `yarn build` and run it locally e.g. `serve -s build` you will get the bug that is happening above. I do not know what is causing this though :D

**Comment by rashadatjou** [comment] 2023-03-03 09:18
@nocive this might help

From the README: 

[Standard instructions](https://github.com/wojtekmaj/react-pdf/issues/782#standard-browserify-esbuild-and-others) will also work with Create React App. Please note that in Create React App, you can copy `pdf.worker.js` file from `pdfjs-dist/build` to `public` directory in order for it to be copied to your project's output folder at build time. 


Copy over `pdfjs-dist/build/pdf.worker.js` to `public/` when building for production.

**Comment by hsjakobsen** [comment] 2023-03-07 15:30
I managed to solve this issue for both development and production

My setup:
    Browser: Chrome 110 and Firefox 110
    React-PDF version: 6.2.0
    React version: 18.2.0
    Webpack version: 5.64.4 (bundled with react-scripts).
    React-scripts: 5.0.1
    
`import { Document, Page, pdfjs } from 'react-pdf';`
`import 'react-pdf/dist/esm/Page/AnnotationLayer.css';`
`import 'react-pdf/dist/esm/Page/TextLayer.css';`
`pdfjs.GlobalWorkerOptions.workerSrc = './pdf.worker.min.2.16.105.js';`

So what I did was to follow the advice of [zwarrell](https://github.com/zwarrell) and download the pdf.worker.min.js and rename it. See the comment link below:
https://github.com/wojtekmaj/react-pdf/issues/782#issuecomment-1407556622

I put it in my public folder and I put it inside the src to be able to load it while developing. 

In order to have my PDF render properly I imported the following 2 styling files:
`import 'react-pdf/dist/esm/Page/AnnotationLayer.css';`
`import 'react-pdf/dist/esm/Page/TextLayer.css';`

**Comment by Jimlala** [comment] 2023-04-28 02:56
> I am running react-pdf 6.2.2 and had this error. I got everything working with the following. `import { Document, Page, pdfjs } from 'react-pdf';` `pdfjs.GlobalWorkerOptions.workerSrc = '/pdf.worker.min.2.16.105.js'`
> 
> I downloaded the pdf.worker.min.js from this link (https://cdn.jsdelivr.net/npm/pdfjs-dist@2.16.105/build/pdf.worker.min.js) and put it in my public directory named as (pdf.worker.min.2.16.105.js) so I am not dependent on a CDN.
> 
> Hope this helps someone else!
> 
> This library is awesome!

Worked for me too. Thanks.

**Comment by codeWriter6** [comment] 2023-06-09 09:22
My setup:
reacct-pdf: 6.2.2, 
webpack: 4
react: 17.0.2,
Load worker from CDN solve this error. But we have strict CSP policy and load work worker from CDN is not allowed. The import worker configuration posted in the doc does not work. 
Only solution that worked for me is:
```
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry';
pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
```
@wojtekmaj I suggest to add this to the doc.

**Comment by moonkid196** [comment] 2023-08-27 19:01
This final approach seemed to get the file into the build for me, but one tweak: didn't work for my typescript app, due to no declarations file. But simply importing the file was sufficient, then left the existing worker config from the examples:

```typescript
import "pdfjs-dist/build/pdf.worker.entry";
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url,
).toString();
```

**Comment by tarikt-hybird** [comment] 2023-09-27 12:19
If anyone is still facing this issue I have followed this approach: https://github.com/wojtekmaj/react-pdf/issues/852#issuecomment-922400496

By using approach from @codeWriter6 above I resolved the issue in production but faced an annoying issue in the localhost: "Uncaught runtime errors: Worker was terminated". So to fix that as well I followed the link above.

My setup: 

"react": "^16.8.6",
"react-pdf": "^7.4.0"

The fix from @dmr07 from the link above: 

```
import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`; 
```

**Comment by SA-AllesHealth** [comment] 2024-04-23 07:08
> Will work ✅:
> `"react-pdf": "5.2.0" `

How you have fix this issue please tell me

**Comment by teuber789** [comment] 2024-04-28 02:18
> My setup: reacct-pdf: 6.2.2, webpack: 4 react: 17.0.2, Load worker from CDN solve this error. But we have strict CSP policy and load work worker from CDN is not allowed. The import worker configuration posted in the doc does not work. Only solution that worked for me is:
> 
> ```
> import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry';
> pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
> ```
> 
> @wojtekmaj I suggest to add this to the doc.

@wojtekmaj I don't think this issue needs to be reopened, but it is probably worth adding this to the readme like @codeWriter6 suggested. Having struggled with this issue for a couple of days, this is the only solution that ended up working. Interestingly, the solution in the readme did _not_ work, even when copying the worker into the public folder like is done in the create-react-app-5 sample.

**Comment by hppnq127** [comment] 2024-05-15 08:15
T got  the same problem with build not working and normally in local. I have tried copy pdf.worker.min.js to public folder and also tried
import "pdfjs-dist/build/pdf.worker.entry";
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url,
).toString();

but it not working
My version is 8.0.2 
Can any one help me plz.

**Comment by CadeRyan** [comment] 2024-05-22 21:07
This is also an issue that I'm running into, and have tried most of the solutions above to no avail.

Is the current recommended solution to use a specific older version like 6.2.2?

**Comment by sarika-pai** [comment] 2025-01-28 22:59
I am also facing the same issue using pdfjs.worker.min.mjs shows me the same error. Error: Setting up fake worker failed: "require is not defined". tried all the above-mentioned solutions, for extension

**Comment by ryanmlow** [comment] 2025-10-23 03:17
This solution worked for me https://github.com/wojtekmaj/react-pdf/issues/782#issuecomment-1694737677.

On v7.7.3
