### ISSUE TITLE
"export 'EventBus' was not found in 'pdfjs-dist/lib/web/ui_utils'

### ISSUE THREAD

**Issue by sulemanidreesi** [wojtekmaj/react-pdf#659] opened 2020-10-01 05:43 UTC
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I am working in rails 6 app and within rails 6 app i'm creating one of my module in react and in that module i'm using react-pdf library but somehow i'm getting this error when i'm importing react-pdf components from react-pdf library:
`ERROR in ./node_modules/react-pdf/dist/esm/eventBus.js`
`"export 'EventBus' was not found in 'pdfjs-dist/lib/web/ui_utils'`
i'm getting above error when i wrote like this
`import {Document, Page, pdfjs} from 'react-pdf';`
but i'm not getting error when i wrote like this 
`const pdfjs = require('pdfjs-dist/es5/build/pdf');`
 
i have also tried to create a separate react app from scratch and follow the getting started example and it is working perfectly in react app
Any idea guys where i'm going wrong?

**Comment by wojtekmaj** [comment] 2020-10-05 12:56
What's the react-pdf version?

Looks like the problem is in [this file](https://github.com/wojtekmaj/react-pdf/blob/master/src/eventBus.js) which imports EventBus from [this file](https://github.com/mozilla/pdf.js/blob/master/web/ui_utils.js) and reexports it. This file, however, definitely has EventBus export 🤔 

Perhaps try somewhere in your code to check what gets exported properly:

```js
import * as UIUtils from 'pdfjs-dist/lib/web/ui_utils';

console.log(UIUtils);
console.log(UIUtils.EventBus);
```

**Comment by trouvainGregoire** [comment] 2020-10-08 10:56
I have the same issue :

Error with `import {Document, Page, pdfjs} from 'react-pdf';` but not with `const pdfjs = require('pdfjs-dist/es5/build/pdf');
`

Even if there is no compilation error with `const pdfjs = require('pdfjs-dist/es5/build/pdf');
` 
In web inspector console i have `TypeError: Cannot set property 'pdfjsLib' of undefined
`

react version : `16.13.1`
react-pdf version : `5.0.0`
rails version : `6.0.3.2`

I have `"export 'EventBus' (imported as 'UIUtils') was not found in 'pdfjs-dist/lib/web/ui_utils'`

When 

import * as UIUtils from 'pdfjs-dist/lib/web/ui_utils';

console.log(UIUtils);
console.log(UIUtils.EventBus);

**Comment by AleksandraKaminska** [comment] 2020-10-08 13:45
I had the same problem and noticed that in my yarn.lock file `pdfjs-dist` has version 2.1 instead of 2.4.

**Comment by wojtekmaj** [comment] 2020-10-09 09:02
Are you by any chance trying to run React-PDF server-side?

**Comment by trouvainGregoire** [comment] 2020-10-09 09:21
> Are you by any chance trying to run React-PDF server-side?

No, it's client-side

I use [https://github.com/reactjs/react-rails](url) gem

**Comment by wojtekmaj** [comment] 2020-10-09 09:55
> I use https://github.com/reactjs/react-rails gem

> * Automatically renders React server-side and client-side

🤔 I think there's your problem. You can't render PDF's server-side.

**Comment by trouvainGregoire** [comment] 2020-10-09 10:08
> * Automatically renders React server-side and client-side
> 
> 🤔 I think there's your problem. You can't render PDF's server-side.

🤔  but server-side it's not enabled by default and i have  `prerender:false` https://github.com/reactjs/react-rails#server-side-rendering

**Comment by imustafin** [comment] 2020-10-12 10:36
I also use `react-rails`. With react-pdf 5 I also get the same errors when importing as `import { pdfjs, Document, Page } from 'react-pdf'`:

```
ERROR in ./node_modules/react-pdf/dist/esm/eventBus.js 2:19-27
"export 'EventBus' was not found in 'pdfjs-dist/lib/web/ui_utils'
    at HarmonyImportSpecifierDependency._getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1463:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/app_name/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1253:28)
    at /var/www/app_name/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1185:12
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

ERROR in ./node_modules/react-pdf/dist/esm/entry.js 11:0-5
"export 'default' (imported as 'pdfjs') was not found in 'pdfjs-dist/build/pdf'
    at HarmonyImportSpecifierDependency._getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1463:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/app_name/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1253:28)
    at /var/www/app_name/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1185:12
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

ERROR in ./node_modules/react-pdf/dist/esm/Document.js 95:28-33
"export 'default' (imported as 'pdfjs') was not found in 'pdfjs-dist/build/pdf'
    at HarmonyImportSpecifierDependency._getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1463:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/app_name/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1253:28)
    at /var/www/app_name/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1185:12
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

ERROR in ./node_modules/react-pdf/dist/esm/Document.js 196:34-39
"export 'default' (imported as 'pdfjs') was not found in 'pdfjs-dist/build/pdf'
    at HarmonyImportSpecifierDependency._getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1463:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/app_name/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1253:28)
    at /var/www/app_name/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1185:12
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

ERROR in ./node_modules/react-pdf/dist/esm/Page/AnnotationLayer.js 191:8-13
"export 'default' (imported as 'pdfjs') was not found in 'pdfjs-dist/build/pdf'
    at HarmonyImportSpecifierDependency._getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1463:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/app_name/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1253:28)
    at /var/www/app_name/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1185:12
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

ERROR in ./node_modules/react-pdf/dist/esm/Page/PageSVG.js 89:25-30
"export 'default' (imported as 'pdfjs') was not found in 'pdfjs-dist/build/pdf'
    at HarmonyImportSpecifierDependency._getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1463:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/app_name/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1253:28)
    at /var/www/app_name/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1185:12
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

ERROR in ./node_modules/react-pdf/dist/esm/entry.js 12:0-42
"export 'default' (reexported as 'pdfjs') was not found in 'pdfjs-dist/build/pdf'
    at HarmonyExportImportedSpecifierDependency._getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:395:11)
    at HarmonyExportImportedSpecifierDependency.getErrors (/var/www/app_name/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:354:16)
    at Compilation.reportDependencyErrorsAndWarnings (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1463:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/app_name/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/var/www/app_name/node_modules/webpack/lib/Compilation.js:1253:28)
    at /var/www/app_name/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/var/www/app_name/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:22)
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1185:12
    at /var/www/app_name/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Now I use an older version of react-pdf (4.0.6), everything works there.

**Comment by srachner** [comment] 2020-11-02 09:28
I had the same issue and managed to get it working by excluding the pdfjs-dist folder from babel transpilation through adding the following to my environment.js file, as described [here](https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader) 

```
const nodeModulesLoader = environment.loaders.get('nodeModules')
if (!Array.isArray(nodeModulesLoader.exclude)) {
    nodeModulesLoader.exclude = (nodeModulesLoader.exclude == null)
        ? []
        : [nodeModulesLoader.exclude]
}
nodeModulesLoader.exclude.push(/pdfjs-dist/)
```

**Comment by ramaboo** [comment] 2021-02-16 14:44
Also ran into this issue and the code above fixed it but a cleaner solution would be great.

**Comment by wojtekmaj** [comment] 2021-03-18 09:46
All,
please kindly help me with testing the fix for this issue.
➡️ https://github.com/wojtekmaj/react-pdf/issues/748

Thanks!

**Closed** 2021-04-01 12:39 UTC
Labels: bug

**Comment by TeemuKoivisto** [comment] 2021-04-13 09:03
Having the unfortunate job of fixing this problem and since this thread seems to come up first in the Google results, I'll just post my own fix here. So what happened was the pdfjs stopped supporting es5 (see https://github.com/mozilla/pdf.js/issues/13190) out of the box and now you have to do a little dance to keep your code es5 compatible. Eg.

```ts
import { getDocument, GlobalWorkerOptions } from 'pdfjs-dist/es5/build/pdf'
import * as pdfjsWorker from 'pdfjs-dist/es5/build/pdf.worker.entry'
import { EventBus, PDFViewer } from 'pdfjs-dist/es5/web/pdf_viewer'
import {
  PDFDocumentLoadingTask,
  PDFDocumentProxy,
  // eslint-disable-next-line import/no-unresolved
} from 'pdfjs-dist/types/display/api'
```

And you probably have to patch the types by yourself too:

```ts
declare module 'pdfjs-dist/es5/build/pdf' {
  export * from 'pdfjs-dist'
}
declare module 'pdfjs-dist/es5/build/pdf.worker.entry'
declare module 'pdfjs-dist/es5/web/pdf_viewer'
```
