### ISSUE TITLE
Chrome <= 91 not working

### ISSUE THREAD

**Issue by guoyunhe** [wojtekmaj/react-pdf#1220] opened 2022-12-12 07:14 UTC
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

In README, this package supports Chrome ≥76. But my react-pdf app doesn't work on Chrome 76 to 91.

It throws:

```
t.split(...).at() is not a function
```

Array.at() is a ES2021 feature, which is too new for Chrome 76 to 91.

### Steps to reproduce

1. Install Chrome 90, or use BrowserStack.
2. Go to https://onetouch.alibaba.com/moBasedata/luyou/public/tas-9710-white-paper-weixin
3. See if the PDF can be rendered.

### Expected behavior

PDF should be rendered

### Actual behavior

Nothing rendered. Console throws errors.

### Environment

- **Browser (if applicable)**: Chrome 90
- **React-PDF version**: 6.2.0
- **React version**: 16.8.0
- **Webpack version (if applicable)**: 5.72.0

**Comment by guoyunhe** [comment] 2022-12-12 07:39
My current workaround is to use webpack/rollup/esbuild's alias to force use legacy pdf.js build:

```json
{
  "alias": {
    "pdfjs-dist/build/pdf": "pdfjs-dist/legacy/build/pdf"
  }
}
```

**Comment by Jannerzhang** [comment] 2022-12-30 08:23
This bug only exists in version 6 and up. You can also switch to 5.X to avoid this bug

**Comment by dbouclier** [comment] 2023-01-27 09:48
I have also a similar error on Safari 14.3 on Iphone 11

`Error: u.split("+").at is not a function. (In 'u.split("+").at(-1)', 'u.split("+").at' is undefined)`

using 
"react-pdf": "^6.2.2",
"react": "^18.2.0",
"webpack": "^5.75.0"

I guess it's also related to the version of the pdf-js used in react-pdf
https://github.com/mozilla/pdf.js/issues/15437
https://github.com/mozilla/pdf.js/issues/15411

**Comment by laghamn** [comment] 2023-02-14 19:37
Have just experienced the same problem but with Safari 14.1, which should be supported according to documentation. Confirmed with minimal Vite template project.

The following does not match...

Package documentation:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/61837005/218839202-91e0c8f9-d644-451f-9eb7-67ea712fc2a0.png">


Array.prototype.at
<img width="768" alt="image" src="https://user-images.githubusercontent.com/61837005/218838930-3810408c-c9d6-436d-93a3-1b8195eca501.png">

**Comment by wojtekmaj** [comment] 2023-04-18 19:46
Since browser requirements are updated in the latest version, I'm closing this issue.

**Closed by wojtekmaj** 2023-04-18 19:46 UTC
Labels: bug
