### ISSUE TITLE
production use terser-webpack-plugin no show

### ISSUE THREAD

**Issue by poohlaha** [wojtekmaj/react-pdf#1681] opened 2023-12-20 03:23 UTC
### Description

I use the `terser webpack plugin` plugin with `webpack5` in a production environment:

```
minimizer.push(new TerserWebpackPlugin())
```

I saw that all the nodes in canvas were loaded, and the text was also cut.

![image](https://github.com/wojtekmaj/react-pdf/assets/10954901/8a2f93d7-b2d8-4550-a74c-a12126840ef2)

A blank space page

It's okay in the testing environment。

```
env:
react: 18.2.0
react-pdf: 7.6.0
webpack: 5.88.2
terser-webpack-plugin: 5.3.9
```

### Environment

- **Browser (if applicable)**: chrome
- **React-PDF version**: 18.2.0
- **React version**: 7.6.0
- **Webpack version (if applicable)**:  5.88.2
terser-webpack-plugin: 5.3.9

**Comment by wojtekmaj** [comment] 2024-01-10 10:23
For starters, I don't understand why would you manually add terser-webpack-plugin if that's what Webpack uses for minification out of the box 🤔 

I was not able to reproduce your issue on included Webpack 5 sample. When building for production and serving the output directory using `serve` I got, as expected:

<img width="1470" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/5426427/37b7b628-68ee-422c-84a8-87b97681be17">

**Comment by wojtekmaj** [comment] 2024-02-01 10:14
I'm closing this because of no reply, but I'm happy to look into this if a reproducible example is provided.

**Closed by wojtekmaj** 2024-02-01 10:14 UTC
Labels: bug
